[[entities]]
  entity = "eyesinthedarkness:eyes"
  minTier = 0
  maxTier = 4
  presetAffixes = []
  affixList = ["adaptable", "arctic", "dampening", "desecrating", "enkindling", "hasty", "infested", "knocking", "lively", "magnetic", "molten", "paralyzing", "plagued", "reflective", "shielding", "wounding"]
  affixPermission = "BLACKLIST"
  
[[entities]]
  entity = "artifacts:mimic"
  minTier = 0
  maxTier = 4
  presetAffixes = []
  affixList = ["adaptable", "arctic", "dampening", "desecrating", "enkindling", "hasty", "infested", "knocking", "lively", "magnetic", "molten", "paralyzing", "plagued", "reflective", "shielding", "wounding"]
  affixPermission = "BLACKLIST"