
[general]
	#If false, the eyes entity will not spawn naturally during the night-
	enableNaturalSpawn = true
	#If -1, the default spawn weight will be used.
	#Range: > -1
	overrideWeight = -1
	#Range: > 1
	minimumPackSize = 1
	#Range: > 1
	maximumPackSize = 1
	#Specifies rules for accepting or rejecting biomes.
	#The rules are scanned one by one until a rule matches, This means the first rule to match takes precedence over any other subsequent rule, so more specific rules should go first.
	#Rules:
	#  "biome:name"    -- ALLOWS spawning in the given biome.
	#  "!biome:name"   -- DISALLOWS spawning in the given biome.
	#  "#biome_label"  -- ALLOWS spawning in the given biome dictionary label.
	#  "!#biome_label" -- DISALLOWS spawning in the given biome dictionary label.
	#  "!*"            -- DISALLOWS spawning unconditionally. Place this at the end of the list to disable spawning if no other rules pass (defaults to allow otherwise).
	#Examples:
	#  To disable spawning in the end: [ "!#END" ]
	#  To disable spawning in the nether biome: [ "!minecraft:nether" ]
	#  To disable spawning in forest areas, but allow them in dark fores: [ "minecraft:dark_forest", "!#FOREST" ]
	#NOTE: VOID type biomes are disabled by default, internally. You can explicitly enable those by adding "#VOID" to the rules, but this is not recommended.
	biomeRules = ["byg:bayou", "byg:polluted_lake", "byg:embur_bog", "byg:black_forest_hills", "byg:dead_sea", "!*"]
	#Set to false to disable the jumpscare system.
	jumpscare = true
	#Set to a number > 0 to cause the jumpscare to apply poison the player. A value of 5 will take around half of the health. 
	#Range: 0 ~ 6
	jumpscareHurtLevel = 1
	#While set to true, the eyes entity will ignore the artificial light level and will jumpscare even if it's lit. Daylight will still disable it's AI.
	eyesCanAttackWhileLit = true

[eye_aggression]
	#While set to true, the eyes entities will progressively get more bold, and move faster, the longer they live.
	enableEscalation = true
	#While set to true, the eyes entities will spawn with higher aggresion levels in higher local difficulties.
	localDifficulty = true
	#While set to true, the eyes entities will have higher aggression values on lower light levels.
	lightLevel = true

