
["Froglin Behaviour"]
	#Time in ticks after a froglin kills something before it becomes hungry again
	#Range: > 0
	froglin_fullness_from_kill = 18000
	#How often (every n ticks) a digging froglin attempts to dig downwards. Increasing this value reduces the rate at which froglins check the blockstates below them
	#Range: > 1
	froglin_dig_frequency = 20
	#Average frequency (roughly every n ticks) at which a well-fed froglin attempts to lay an egg in water
	#Range: > 1
	froglin_egg_frequency = 100

["Froglin Eggs"]
	#Froglins marked as persistant will lay eggs that hatch into persistant froglins
	persistant_froglins_lay_persistant_froglin_eggs = false
	#Froglin eggs placed by players hatch into persistant froglins
	players_place_persistant_froglin_eggs = false

