#Maximum amount of blocks that can be locked at once
#Range: > 0
"Max Lockable Volume" = 6
#Blocks that can be locked. Syntax is the mod domain followed by the block's registry name. Can include regular expressions
"Lockable Blocks" = ["minecraft:.*chest", "minecraft:chest_minecart", "minecraft:barrel", "minecraft:dispenser", "minecraft:dropper", "minecraft:hopper", "minecraft:.*door", "minecraft:.*trapdoor", "minecraft:.*fence_gate", "minecraft:.*shulker_box", "metalbarrels:.*barrel", "ironchests:.*chest", "variant16x:.*gate", "byg:.*gate", "moblocks:.*gate", "bambooeverything:.*gate", "mekanismadditions:.*gate", "forbidden_arcanus:.*door", "forbidden_arcanus:.*trapdoor", "byg:.*door", "byg:.*trapdoor", "bambooeverything:.*door", "bambooeverything:.*trapdoor", "silentgear:.*door", "silentgear:.*trapdoor", "mcwdoors:.*door", "mcwdoors:.*trapdoor", "storagedrawers:.*drawers_1", "storagedrawers:.*drawers_2", "storagedrawers:.*drawers_4", "storagedrawers:.*drawers_3", "moblocks:.*drawer", "buildersaddition:beside_table.*", "buildersaddition:cabinet.*", "buildersaddition:counter.*", "cookingforblockheads:counter", "cookingforblockheads:cabinet", "cookingforblockheads:fridge"]
#Open locks can be removed with an empty hand while sneaking
"Allow Removing Locks" = true
#Locked blocks cannot be destroyed in survival mode
"Protect Lockables" = true
#All lock items, which don't have a length nbt value will have this value set as their length. The length of a lock can still be changed by editing its nbt
#Range: 1 ~ 30
"Default Lock Length" = 5
#All lock pick items which don't have a strength nbt value will have this value set as their strength. The strength of a lock pick can still be changed by edition its nbt
#Range: 0.0 ~ 1.0
"Default Lock Pick Strength" = 1.0

