#Preferences for outputs from tags used in automatic compat in recipes
tagPreferences = ["create", "eidolon", "druidcraft", "occultism", "mysticalworld", "mekanism", "immersiveengineering", "tconstruct", "minecraft"]

