#The blocks that should get harvested by right-clicking
reap_whitelist = ["minecraft:nether_wart", "minecraft:potatoes", "minecraft:carrots", "minecraft:wheat", "minecraft:beetroots", "minecraft:cocoa", "peanutmod:peanut_crop", "veggie_way:plant_lentil", "veggie_way:plant_corn", "veggie_way:plant_soybean", "veggie_way:plant_quinoa"]
#Examples: 'minecraft:oak_log', '#minecraft:logs'
log_types = ["#minecraft:logs"]
#Examples: 'minecraft:dirt', '#forge:sand/colorless'
ground_types = ["minecraft:dirt", "minecraft:grass_block", "minecraft:coarse_dirt", "minecraft:podzol", "minecraft:mycelium", "minecraft:warped_nylium", "minecraft:crimson_nylium", "minecraft:netherrack"]
#The tools which the player is allowed to harvest trees
allowed_tree_tools = ["minecraft:wooden_axe", "minecraft:golden_axe", "minecraft:stone_axe", "minecraft:iron_axe", "minecraft:diamond_axe", "minecraft:netherite_axe"]
#If the tree harvester should be enabled
tree_harvest = false
#If bigger trees should be harder to break
dynamic_tree_breaking_speed = true

