#Restock
Restock = true
#Use fixed items
UseFixedItems = false
#Fixed items
FixedItems = "minecraft:air;minecraft:air;minecraft:air;minecraft:air;minecraft:air;minecraft:air;minecraft:air"
#Include Mods
IncludeMods = "toolbelt;chanceglobe;curios;potionofbees;randomloot;jmc;backpacked;packingtape;yeeter;lootbagmod;mystictools;torchmaster;clef;locks;trumpetskeleton;mysterymilk;levelhearts"
#Exclude Mods
ExcludeMods = "*"
#Exclude Items
ExcludeItems = "minecraft:nether_star;minecraft:beacon;minecraft:shulker_box;minecraft:colorset*shulker_box;minecraft:elytra;minecraft:end_portal_frame;vm:vending_machine;randomloot:pickaxe;randomloot:sword;curios:amulet;curios:knuckles;curios:crown;packingtape:packaged_block;jmc:cheese;jmc:golden_apple_cake;jmc:birthday_cake;jmc:christmas_cake;jmc:triple_decker_cake;jmc:cupcake;randomloot:trait_holder;randomloot;randomloot:editor;randomloot:random_cluster;randomloot:random_chunk;randomloot:random_shard;mystictools:cauldron;mystictools:shard;mystictools:weaponbow;mystictools:loot_pickaxe;mystictools:loot_shovel;mystictools:loot_axe;mystictools:loot_sword;locks:master_key;locks:key;trumpetskeleton:trumpet_skeleton_spawn_egg;mystictools:dice;mystictools:charm;mystictools:upgrader;"
#Include Creative Tab Groups
IncludeGroups = "*"
#Exclude Creative Tab Groups
ExcludeGroups = "!"
#Change item rarity value for pricing
ItemRarity = "randomloot:golden_case=1;randomloot:titan_case=2;curios:ring=2;yeeter:tnt_yeeter_spawn_egg=1;lootbagmod:lootbag=2;mystictools:loot_case=2;locks:lock=1;levelhearts:heart_piece=2;levelhearts:heart_container=3"

[RarityData]
	#Uncommon Item
	UncommonItem = "minecraft:emerald"
	#Rare Item
	RareItem = "minecraft:emerald"
	#Uncommon Cost
	#Range: 1 ~ 64
	UncommonCost = 12
	#Rare Uses
	#Range: 1 ~ 32
	RareUses = 2
	#Epic Uses
	#Range: 1 ~ 32
	EpicUses = 1
	#Epic Item
	EpicItem = "minecraft:emerald"
	#Common Item
	CommonItem = "minecraft:emerald"
	#Epic Cost
	#Range: 1 ~ 64
	EpicCost = 24
	#Rare Cost
	#Range: 1 ~ 64
	RareCost = 18
	#Common Uses
	#Range: 1 ~ 32
	CommonUses = 4
	#Uncommon Uses
	#Range: 1 ~ 32
	UncommonUses = 3
	#Common Cost
	#Range: 1 ~ 64
	CommonCost = 6

