
#Biome config
#To filter biomes by registry name "mod_id:biome_id"
#To filter biomes by category "@category"
#To filter biomes by tags "#tag"
#	Examples:
#		"minecraft:plains"
#		"@desert"
#		"#overworld"
#
#If you want to exclude biomes put a ! before the biome identifier
#	Examples:
#		"!minecraft:plains"
#		"!@desert"
#		"!#nether"
#
#If you want to include biomes that would be satisfied by any in a set use |
#	Examples:
#		"|minecraft:plains"
#		"|@desert"
#		"|#nether"
#
#If you want a condition that MUST be satisfied use an & before the biome identifier
#Please note using this on a registry name wouldn't be that useful
#	Examples:
#		"&minecraft:plains"
#		"&@forest"
#		"&#overworld"
#
#NOTE: Any entry without a !, |, or & symbol has a higher precedence
#A list like ["!minecraft:plains", "#overworld"] would still see the plains as a viable biome
#
#Finally, you can create a expression that can be evaluated by itself using a + to combine identifiers
#	Examples:
#		"!#hot+!#dry+!#mountain"
#
#These expressions can be used to filter biomes in a lot of ways
#Lets say we don't want anything to spawn in any place dry and sandy
#	"!#dry+!#sandy"
#
#But there is a hot place we want them to spawn that's also wet
#	"#hot+#wet"
#
#We just put them as separate values in the list and that'll work out
#	["!#dry+!#sandy","#hot+#wet"]
#
#NOTE: Any entry that's an expression will not be affected by anything else in the list
[biome_configs]
	rattlesnake = ["&#overworld+|#mesa+|@desert+|#sandy+|byg:sierra_valley+|byg:red_rock_highlands+|byg:red_rock_lowlands"]
	crocodile = ["&#overworld+|#swamp+|#river+!#cold", "|undergarden:mushroom_bog"]
	gorilla = ["&#overworld+|#jungle+!minecraft:bamboo_jungle+!minecraft:bamboo_jungle_hills+!byg:bamboo_forest+!byg:jacaranda_forest+!byg:jacaranda_forest_hills+!byg:jacaranda_clearing", "|rats:ratlantis_biome"]
	komodoDragon = ["&#overworld+|#mesa+|byg:sierra_valley+|byg:red_rock_highlands+|byg:red_rock_lowlands"]
	lobster = ["&#overworld+|#beach", "|more_jellyfish:rock_bottom"]
	sunbird = ["|byg:guiana_clearing+|gaiadimension:shining_grove+|byg:tropical_islands+|byg:oasis+|byg:skyris_highlands"]
	boneSerpent = ["|#nether+|good_nights_sleep:shameful_plains+|good_nights_sleep:nightmare_hills+|mining_dimension:mining"]
	moose = ["&#overworld+|#snowy+&#wasteland", "&#overworld+|#snowy+&#forest"]
	gazelle = ["&#overworld+|@savanna+|#savanna", "|good_nights_sleep:good_dream_plains"]
	hammerheadShark = ["&#overworld+|#ocean+!#cold"]
	caveCentipede = ["&#overworld+!#water+!#mushroom", "|mining_dimension:mining"]
	warpedToad = ["|minecraft:warped_forest+|byg:glowstone_gardens"]
	fly = ["&#overworld+!@ocean+!#ocean+!#cold", "|undergarden:gronglegrowth+|the_bumblezone:hive_pillar"]
	orca = ["&#overworld+|#ocean+!#hot+!byg:dead_sea"]
	hummingbird = ["|minecraft:flower_forest+|minecraft:sunflower_plains+|byg:allium_fields+|byg:amaranth_fields+|byg:rose_fields+|byg:flowering_ancient_forest+|byg:flowering_enchanted_grove+|byg:flowering_grove+|byg:flowering_meadow+|byg:enchanted_forest+|byg:enchanted_forest_hills+|byg:enchanted_grove+|good_nights_sleep:lollipop_lands+|gaiadimension:green_agate_jungle+|#jungle"]
	grizzlyBear = ["&#overworld+|@forest+!#hot|#forest+!#hot"]
	endergrade = ["&#end+!minecraft:the_end"]
	capuchinMonkey = ["&#overworld+|#jungle+!minecraft:bamboo_jungle+!minecraft:bamboo_jungle_hills+!byg:bamboo_forest", "|rats:ratlantis_biome"]
	crimsonMosquito = ["|minecraft:crimson_forest+|byg:crimson_gardens+|byg:shattered_viscal_isles"]
	roadrunner = ["&#overworld+|@desert+|#sandy+!#water+!#beach"]
	mimicube = ["&#end+!minecraft:the_end", "|byg:shulkren_forest"]
	raccoon = ["&#overworld+|@forest+!#dry+!#water+!#hot+|#forest+!#dry+!#water+!#hot"]
	blobfish = ["|minecraft:deep_ocean+|minecraft:deep_cold_ocean+|minecraft:deep_frozen_ocean+|minecraft:deep_lukewarm_ocean+|rats:ratlantis_biome"]
	seal = ["&#overworld+|#beach", "&#overworld+|#ocean+&#snowy"]
	cockroach = ["&#overworld+!#ocean+!#mushroom+!#dry+!#magical", "|undergarden:barren_abyss+|good_nights_sleep:wasted_forest+|gaiadimension:volcanic_lands+|byg:sythian_torrids+|mining_dimension:mining"]
	shoebill = ["&#overworld+|#swamp"]
	elephant = ["&#overworld+|@savanna+!#plateau|#savanna+!#plateau"]
	soulVulture = ["|minecraft:soul_sand_valley+|byg:warped_desert"]
	snowLeopard = ["&#overworld+|#snowy+&#mountain"]
	spectre = ["|minecraft:small_end_islands"]
	crow = ["&#overworld+!#savanna+!#@savanna+|@forest+|#forest+|@plains+|#plains"]

