
#General Settings
[general]
	#Max number of notes played per 20 ticks.
	#Range: 0 ~ 200
	midi_note_limit = 75
	#Enable server MIDI.
	midi_enable = true
	#Enable MIDI client sound.
	midi_sound_enable = true
	#Enable MIDI input.
	midi_input_enable = false

