
#BYG WorldType Settings
[World_Settings]
	#Vanilla BiomeSounds. Default is true
	VanillaBiomes = true
	#Add external COOL biomes by their registry names in a commented list.
	ExternalCOOLBiomes = ""
	#Add external ICY biomes by their registry names in a commented list.
	ExternalICYBiomes = ""
	#Biome Size, Default 1.
	#Range: 0 ~ 25
	BiomeSize = 1
	#Add external WARM biomes by their registry names in a commented list.
	ExternalWARMBiomes = ""
	#Add external HOT biomes by their registry names in a commented list.
	ExternalHOTBiomes = ""

	[World_Settings.Stone_Settings]

		[World_Settings.Stone_Settings.Soapstone]
			#Range: 0 ~ 100
			SoapstoneChance = 8
			#Range: 0 ~ 256
			SoapstoneMaxY = 12
			#Range: 0 ~ 35
			SoapstoneSize = 20

		[World_Settings.Stone_Settings.Scoria_Stone]
			#Range: 0 ~ 100
			ScoriaStoneChance = 8
			#Range: 0 ~ 256
			ScoriaStoneMaxY = 24
			#Range: 0 ~ 35
			ScoriaStoneSize = 20

		[World_Settings.Stone_Settings.Rocky_Stone]
			#Range: 0 ~ 100
			RockyStoneSize = 10
			#Range: 0 ~ 100
			RockyStoneChance = 4
			#Range: 0 ~ 256
			RockyStoneMaxY = 256

	#External Biomes
	[World_Settings.Dimension_Settings]
		#Add external Nether biomes by their registry names in a commented list.
		ExternalNetherBiomes = ""
		#Add external End biomes by their registry names in a commented list.
		ExternalEndBiomes = ""

	[World_Settings.Ore_Settings]

		#Pendorite is exclusive to Forest Fault!
		[World_Settings.Ore_Settings.Pendorite]
			#Range: 0 ~ 256
			PendoriteMaxY = 56
			#Range: 0 ~ 16
			PendoriteSize = 4
			#Range: 0 ~ 100
			PendoriteChance = 10

		#Ametrine is exclusive to Guiana Shield!
		[World_Settings.Ore_Settings.Ametrine]
			#Range: 0 ~ 100
			AmetrineChance = 10
			#Range: 0 ~ 256
			AmetrineMaxY = 56
			#Range: 0 ~ 16
			AmetrineSize = 4

