
[Stone_Settings]

	[Stone_Settings.Soapstone]
		#Range: 0 ~ 100
		SoapstoneChance = 10
		#Range: 0 ~ 256
		SoapstoneMaxY = 30
		#Range: 0 ~ 35
		SoapstoneSize = 24

	[Stone_Settings.Scoria_Stone]
		#Range: 0 ~ 100
		ScoriaStoneChance = 10
		#Range: 0 ~ 256
		ScoriaStoneMaxY = 20
		#Range: 0 ~ 35
		ScoriaStoneSize = 24

	[Stone_Settings.Rocky_Stone]
		#Range: 0 ~ 100
		RockyStoneSize = 0
		#Range: 0 ~ 100
		RockyStoneChance = 4
		#Range: 0 ~ 256
		RockyStoneMaxY = 256

#External Biomes. World settings for custom nether/end/byg: https://gist.github.com/CorgiTaco/f5716864bc7b63b04aa547ccfc0e846a
[Dimension_Settings]
	#Add external Nether biomes by their registry names in a commented list.
	ExternalNetherBiomes = "biomesoplenty:crystalline_chasm"
	#Add external End biomes by their registry names in a commented list.
	ExternalEndBiomes = ""
	#Add external Nether biomes by their registry names in a commented list.
	#Range: 0 ~ 10
	EndBiomeSize = 2
	#Add external Nether biomes by their registry names in a commented list.
	#Range: 0 ~ 10
	NetherBiomeSize = 2

[Ore_Settings]

	#Pendorite is exclusive to Forest Fault!
	[Ore_Settings.Pendorite]
		#Range: 0 ~ 256
		PendoriteMaxY = 56
		#Range: 0 ~ 16
		PendoriteSize = 4
		#Range: 0 ~ 100
		PendoriteChance = 10

	#Ametrine is exclusive to Guiana Shield!
	[Ore_Settings.Ametrine]
		#Range: 0 ~ 100
		AmetrineChance = 10
		#Range: 0 ~ 256
		AmetrineMaxY = 56
		#Range: 0 ~ 16
		AmetrineSize = 4

#BYG WorldType Settings
[World_Settings]
	#Vanilla BiomeSounds. Default is true
	VanillaBiomes = true
	#Add external COOL biomes by their registry names in a commented list.
	ExternalCOOLBiomes = "biomesoplenty:boreal_forest,biomesoplenty:meadow,biomesoplenty:fir_clearing,biomesoplenty:coniferous_forest,biomesoplenty:maple_woods,biomesoplenty:seasonal_forest,biomesoplenty:silkglade,biomesoplenty:woodland,biomesoplenty:tundra,biomesoplenty:dead_forest,biomesoplenty:ghost_forest,biomesoplenty:pumpkin_patch,biomesoplenty:shield,biomesoplenty:flower_meadow,biomesoplenty:mire"
	#Add external ICY biomes by their registry names in a commented list.
	ExternalICYBiomes = "biomesoplenty:alps,biomesoplenty:alps_foothills,biomesoplenty:snowy_coniferous_forest,biomesoplenty:snowy_fir_clearing,biomesoplenty:snowy_forest,biomesoplenty:cold_desert"
	#Biome Size, Default 1.
	#Range: 0 ~ 25
	BiomeSize = 4
	#Add external WARM biomes by their registry names in a commented list.
	ExternalWARMBiomes = "biomesoplenty:temperate_rainforest,biomesoplenty:temperate_rainforest_hills,biomesoplenty:tropic_beach,biomesoplenty:tropics,biomesoplenty:rainforest,biomesoplenty:marsh,biomesoplenty:bog,biomesoplenty:prairie,biomesoplenty:pasture,biomesoplenty:chaparral,biomesoplenty:mangrove,biomesoplenty:orchard,biomesoplenty:lavender_field,biomesoplenty:poppy_field,biomesoplenty:cherry_blossom_grove,biomesoplenty:origin_beach,biomesoplenty:origin_hills,biomesoplenty:ominous_woods,biomesoplenty:gravel_beach,biomesoplenty:grove,biomesoplenty:grassland,biomesoplenty:wetland,biomesoplenty:mystic_grove,biomesoplenty:shrubland,biomesoplenty:highland,biomesoplenty:highland_moor,biomesoplenty:steppe,biomesoplenty:rainbow_valley,biomesoplenty:redwood_forest,biomesoplenty:redwood_forest_edge,biomesoplenty:fungal_jungle"
	#Add external HOT biomes by their registry names in a commented list.
	ExternalHOTBiomes = "biomesoplenty:brushland,biomesoplenty:oasis,biomesoplenty:outback,biomesoplenty:scrubland,biomesoplenty:tropical_rainforest,biomesoplenty:wasteland,biomesoplenty:xeric_shrubland,biomesoplenty:volcano,biomesoplenty:volcano_edge,biomesoplenty:lush_grassland,biomesoplenty:lush_swamp,biomesoplenty:floodplain,biomesoplenty:bayou,biomesoplenty:overgrown_cliffs"

