
["spawn chance"]
	#Configure spawn weight and group size.
	#Range: 0 ~ 64
	min = 2
	#Range: 0 ~ 64
	max = 4
	#Range: 0 ~ 100
	weight = 3

["spawn biomes"]
	"biome categories" = ["plains"]
	"biomes (resourcelocation)" = []

[normalCorgi]
	#Is the trait active?
	Active = true

[fabbe50Corgi]
	#Is the trait active?
	Active = true

[bodyguardCorgi]
	#Is the trait active?
	Active = true

[businessCorgi]
	#Is the trait active?
	Active = true

[melonCorgi]
	#Is the trait active?
	Active = true
	#Should the Melon Corgi break melons?
	Break = true

[pirateCorgi]
	#Is the trait active?
	Active = true

[spyCorgi]
	#Is the trait active?
	Active = true

[sunglassesCorgi]
	#Is the trait active?
	Active = true

[antiCorgi]
	#Is the trait active?
	Active = true

[loveCorgi]
	#Is the trait active?
	Active = true
	#How long should the range be? (radius)
	#Range: 0 ~ 30
	Range = 5
	#Is the particle effect active?
	Particles = true

[radioactiveCorgi]
	#Is the trait active?
	Active = true
	#How long should the range be? (radius)
	#Range: 0 ~ 30
	Range = 5
	#Is the particle effect active?
	Particles = true

[heroCorgi]
	#Is the trait active?
	Active = true

[nerdCorgi]
	#Is the trait active?
	Active = true

