
[worldgen]

	#
	#Modify Create's impact on your terrain
	[worldgen.v1]
		#
		#Prevents all worldgen added by Create from taking effect
		disableWorldGen = false
		#
		#Forward caught TileEntityExceptions to the log at debug level.
		logTeErrors = false

		[worldgen.v1.copper_ore]
			#
			#Whether to spawn this in your World
			enable = false
			#
			#Range: > 0
			clusterSize = 18
			#
			#Range: > 0
			clusterCount = 2
			#
			#Range: > 0
			minHeight = 40
			#
			#Range: > 0
			maxHeight = 86

		[worldgen.v1.copper_ore_ocean]
			#
			#Whether to spawn this in your World
			enable = false
			#
			#Range: > 0
			clusterSize = 15
			#
			#Range: > 0
			clusterCount = 4
			#
			#Range: > 0
			minHeight = 20
			#
			#Range: > 0
			maxHeight = 55

		[worldgen.v1.zinc_ore]
			#
			#Whether to spawn this in your World
			enable = true
			#
			#Range: > 0
			clusterSize = 7
			#
			#Range: > 0
			clusterCount = 3
			#
			#Range: > 0
			minHeight = 42
			#
			#Range: > 0
			maxHeight = 255

		[worldgen.v1.zinc_ore_desert]
			#
			#Whether to spawn this in your World
			enable = true
			#
			#Range: > 0
			clusterSize = 8
			#
			#Range: > 0
			clusterCount = 4
			#
			#Range: > 0
			minHeight = 12
			#
			#Range: > 0
			maxHeight = 42

		[worldgen.v1.limestone]
			#
			#Whether to spawn this in your World
			enable = true
			#
			#Range: > 0
			clusterSize = 100
			#
			#Range: 0.0 ~ 1.0
			clusterChance = 0.04
			#
			#Range: > 0
			minHeight = 42
			#
			#Range: > 0
			maxHeight = 255

		[worldgen.v1.weathered_limestone]
			#
			#Whether to spawn this in your World
			enable = true
			#
			#Range: > 0
			clusterSize = 100
			#
			#Range: 0.0 ~ 1.0
			clusterChance = 0.04
			#
			#Range: > 0
			minHeight = 12
			#
			#Range: > 0
			maxHeight = 42

		[worldgen.v1.dolomite]
			#
			#Whether to spawn this in your World
			enable = true
			#
			#Range: > 0
			clusterSize = 100
			#
			#Range: 0.0 ~ 1.0
			clusterChance = 0.02
			#
			#Range: > 0
			minHeight = 20
			#
			#Range: > 0
			maxHeight = 255

		[worldgen.v1.gabbro]
			#
			#Whether to spawn this in your World
			enable = true
			#
			#Range: > 0
			clusterSize = 100
			#
			#Range: 0.0 ~ 1.0
			clusterChance = 0.02
			#
			#Range: > 0
			minHeight = 20
			#
			#Range: > 0
			maxHeight = 255

		[worldgen.v1.scoria]
			#
			#Whether to spawn this in your World
			enable = true
			#
			#Range: > 0
			clusterSize = 100
			#
			#Range: 0.0 ~ 1.0
			clusterChance = 0.04
			#
			#Range: > 0
			minHeight = 0
			#
			#Range: > 0
			maxHeight = 12

