
[general]
	#Frequency of mud lake generation. Lower number -> High appearance chance
	#Range: > 1
	mudLakeFrequency = 50

[entities]

	[entities.inkySheep]
		#Minimum number of entities in group
		#Range: > 0
		entityGroupMin = 2
		#Maximum number of entities in group
		#Range: > 0
		entityGroupMax = 3
		#Biome where entity Spawn
		spawnBiomes = ["minecraft:wooded_mountains", "minecraft:mountain_edge", "byg:cold_swamplands", "byg:boreal_forest"]
		#Weight of entity in spawn
		#Range: > 0
		entityWeight = 10

	[entities.sunsetCow]
		#Minimum number of entities in group
		#Range: > 0
		entityGroupMin = 2
		#Maximum number of entities in group
		#Range: > 0
		entityGroupMax = 3
		#Biome where entity Spawn
		spawnBiomes = ["minecraft:savanna", "byg:baobab_savanna", "byg:lush_red_desert", "byg:red_desert", "byg:red_desert_dunes", "minecraft:badlands", "minecraft:badlands_plateau", "minecraft:eroded_badlands", "minecraft:modified_badlands_plateau", "minecraft:modified_wooded_badlands_plateau", "minecraft:wooded_badlands_plateau", "byg:red_rock_highlands", "byg:red_rock_lowlands", "byg:red_rock_mountains"]
		#Weight of entity in spawn
		#Range: > 0
		entityWeight = 8

	[entities.midnightChicken]
		#Minimum number of entities in group
		#Range: > 0
		entityGroupMin = 2
		#Maximum number of entities in group
		#Range: > 0
		entityGroupMax = 3
		#Biome where entity Spawn
		spawnBiomes = ["minecraft:dark_forest", "minecraft:dark_forest_hills", "byg:blue_taiga", "byg:blue_taiga_hills", "byg:blue_giant_taiga", "byg:crag_gardens"]
		#Weight of entity in spawn
		#Range: > 0
		entityWeight = 10

	[entities.muddyFootRabbit]
		#Minimum number of entities in group
		#Range: > 0
		entityGroupMin = 2
		#Maximum number of entities in group
		#Range: > 0
		entityGroupMax = 3
		#Biome where entity Spawn
		spawnBiomes = ["byg:prairie", "minecraft:plains", "byg:meadow", "byg:grassland_plateau", "byg:red_desert", "byg:mojave_desert"]
		#Weight of entity in spawn
		#Range: > 0
		entityWeight = 4

	[entities.muddyPig]
		#Minimum number of entities in group
		#Range: > 0
		entityGroupMin = 2
		#Maximum number of entities in group
		#Range: > 0
		entityGroupMax = 3
		#Biome where entity Spawn
		spawnBiomes = ["byg:prairie", "minecraft:plains", "byg:meadow", "minecraft:forest", "minecraft:mountain_edge", "byg:red_desert", "byg:mojave_desert", "byg:grassland_plateau"]
		#Weight of entity in spawn
		#Range: > 0
		entityWeight = 10

	[entities.furnaceGolem]
		#Minimum number of entities in group
		#Range: > 0
		entityGroupMin = 1
		#Maximum number of entities in group
		#Range: > 0
		entityGroupMax = 2
		#Biome where entity Spawn
		spawnBiomes = ["minecraft:plains", "byg:prairie", "byg:wooded_meadow", "byg:orchard", "byg:zelkova_forest"]
		#Weight of entity in spawn
		#Range: > 0
		entityWeight = 18

	[entities.amberChicken]
		#Minimum number of entities in group
		#Range: > 0
		entityGroupMin = 2
		#Maximum number of entities in group
		#Range: > 0
		entityGroupMax = 4
		#Biome where entity Spawn
		spawnBiomes = ["minecraft:desert", "minecraft:desert_hills", "minecraft:desert_lakes", "minecraft:badlands", "minecraft:badlands_plateau", "minecraft:eroded_badlands", "minecraft:modified_badlands_plateau", "minecraft:modified_wooded_badlands_plateau", "minecraft:wooded_badlands_plateau", "byg:prairie", "byg:lush_red_desert", "byg:red_desert", "byg:red_desert_dunes", "byg:red_rock_highlands", "byg:red_rock_lowlands", "byg:red_rock_mountains"]
		#Weight of entity in spawn
		#Range: > 0
		entityWeight = 10

	[entities.melonGolem]
		#Minimum number of entities in group
		#Range: > 0
		entityGroupMin = 2
		#Maximum number of entities in group
		#Range: > 0
		entityGroupMax = 3
		#Biome where entity Spawn
		spawnBiomes = ["minecraft:snowy_taiga", "minecraft:snowy_taiga_hills", "minecraft:snowy_taiga_mountains", "minecraft:snowy_tundra", "minecraft:snowy_mountains", "minecraft:snowy_beach", "minecraft:ice_spikes", "byg:snowy_rocky_black_beach", "byg:snowy_evergreen_hills", "byg:snowy_deciduous_forest_hills", "byg:snowy_coniferous_forest_hills", "byg:snowy_blue_taiga_hills"]
		#Weight of entity in spawn
		#Range: > 0
		entityWeight = 18

	[entities.ashenCow]
		#Minimum number of entities in group
		#Range: > 0
		entityGroupMin = 2
		#Maximum number of entities in group
		#Range: > 0
		entityGroupMax = 3
		#Biome where entity Spawn
		spawnBiomes = ["minecraft:gravelly_mountains", "minecraft:modified_gravelly_mountains", "byg:snowy_black_beach", "byg:weeping_witch_forest", "byg:black_forest_clearing", "byg:ancient_forest"]
		#Weight of entity in spawn
		#Range: > 0
		entityWeight = 8

	[entities.woolyCow]
		#Minimum number of entities in group
		#Range: > 0
		entityGroupMin = 2
		#Maximum number of entities in group
		#Range: > 0
		entityGroupMax = 3
		#Biome where entity Spawn
		spawnBiomes = ["minecraft:ice_spikes", "minecraft:giant_spruce_taiga", "minecraft:giant_tree_taiga", "minecraft:giant_tree_taiga_hills", "minecraft:giant_spruce_taiga_hills", "byg:snowy_blue_giant_taiga", "byg:snowy_evergreen_clearing", "byg:snowy_coniferous_clearing", "byg:snowy_deciduous_clearing"]
		#Weight of entity in spawn
		#Range: > 0
		entityWeight = 8

	[entities.boneSpider]
		#Minimum number of entities in group
		#Range: > 0
		entityGroupMin = 1
		#Maximum number of entities in group
		#Range: > 0
		entityGroupMax = 2
		#Biome where entity Spawn
		spawnBiomes = ["byg:prairie", "minecraft:plains", "minecraft:sunflower_plains", "minecraft:taiga", "minecraft:taiga_hills", "minecraft:taiga_mountains", "minecraft:snowy_taiga", "minecraft:snowy_taiga_hills", "minecraft:snowy_taiga_mountains", "minecraft:giant_tree_taiga", "minecraft:giant_tree_taiga_hills", "minecraft:giant_spruce_taiga", "minecraft:giant_spruce_taiga_hills", "byg:weeping_witch_clearing", "byg:autumnal_valley", "byg:zelkova_forest_hills", "byg:pumpkin_forest", "byg:boreal_forest", "minecraft:bamboo_jungle", "byg:embur_bog", "byg:dead_sea"]
		#Weight of entity in spawn
		#Range: > 0
		entityWeight = 18

	[entities.glowSquid]
		#Minimum number of entities in group
		#Range: > 0
		entityGroupMin = 1
		#Maximum number of entities in group
		#Range: > 0
		entityGroupMax = 2
		#Biome where entity Spawn
		spawnBiomes = ["minecraft:deep_ocean", "minecraft:deep_frozen_ocean", "minecraft:deep_cold_ocean", "minecraft:deep_lukewarm_ocean", "minecraft:deep_warm_ocean"]
		#Weight of entity in spawn
		#Range: > 0
		entityWeight = 6

	[entities.piebaldPig]
		#Minimum number of entities in group
		#Range: > 0
		entityGroupMin = 2
		#Maximum number of entities in group
		#Range: > 0
		entityGroupMax = 3
		#Biome where entity Spawn
		spawnBiomes = ["minecraft:badlands", "minecraft:badlands_plateau", "minecraft:eroded_badlands", "minecraft:modified_badlands_plateau", "minecraft:modified_wooded_badlands_plateau", "minecraft:wooded_badlands_plateau", "byg:sierra_range", "byg:sierra_valley"]
		#Weight of entity in spawn
		#Range: > 0
		entityWeight = 10

	[entities.fleckedSheep]
		#Minimum number of entities in group
		#Range: > 0
		entityGroupMin = 2
		#Maximum number of entities in group
		#Range: > 0
		entityGroupMax = 3
		#Biome where entity Spawn
		spawnBiomes = ["minecraft:wooded_mountains", "minecraft:mountain_edge", "minecraft:taiga", "minecraft:taiga_hills", "minecraft:forest", "minecraft:wooded_hills", "byg:red_rock_highlands", "byg:red_rock_mountains", "byg:cika_mountains"]
		#Weight of entity in spawn
		#Range: > 0
		entityWeight = 10

	[entities.harelequinRabbit]
		#Minimum number of entities in group
		#Range: > 0
		entityGroupMin = 2
		#Maximum number of entities in group
		#Range: > 0
		entityGroupMax = 3
		#Biome where entity Spawn
		spawnBiomes = ["minecraft:taiga", "minecraft:taiga_hills", "minecraft:forest", "minecraft:wooded_hills", "byg:red_rock_lowlands", "minecraft:badlands", "byg:lush_red_desert", "byg:red_desert", "byg:red_desert_dunes", "byg:red_rock_lowlands"]
		#Weight of entity in spawn
		#Range: > 0
		entityWeight = 4

	[entities.stormyChicken]
		#Minimum number of entities in group
		#Range: > 0
		entityGroupMin = 2
		#Maximum number of entities in group
		#Range: > 0
		entityGroupMax = 3
		#Biome where entity Spawn
		spawnBiomes = ["minecraft:taiga", "minecraft:taiga_hills", "minecraft:taiga_mountains", "byg:allium_fields", "byg:ebony_woods"]
		#Weight of entity in spawn
		#Range: > 0
		entityWeight = 10

	[entities.moobloom]
		#Minimum number of entities in group
		#Range: > 0
		entityGroupMin = 2
		#Maximum number of entities in group
		#Range: > 0
		entityGroupMax = 3
		#Biome where entity Spawn
		spawnBiomes = ["minecraft:flower_forest", "byg:amaranth_fields", "byg:allium_fields", "byg:flowering_meadow", "byg:guiana_clearing", "byg:glowing_ancient_forest"]
		#Weight of entity in spawn
		#Range: > 0
		entityWeight = 8

	[entities.palePig]
		#Minimum number of entities in group
		#Range: > 0
		entityGroupMin = 2
		#Maximum number of entities in group
		#Range: > 0
		entityGroupMax = 3
		#Biome where entity Spawn
		spawnBiomes = ["minecraft:snowy_tundra", "minecraft:snowy_mountains", "minecraft:snowy_taiga", "minecraft:snowy_taiga_hills", "minecraft:snowy_taiga_mountains", "byg:snowy_deciduous_forest", "byg:snowy_blue_taiga", "byg:snowy_evergreen_taiga", "byg:snowy_coniferous_forest", "byg:zelkova_clearing", "byg:cherry_blossom_forest"]
		#Weight of entity in spawn
		#Range: > 0
		entityWeight = 10

	[entities.albinoCow]
		#Minimum number of entities in group
		#Range: > 0
		entityGroupMin = 2
		#Maximum number of entities in group
		#Range: > 0
		entityGroupMax = 3
		#Biome where entity Spawn
		spawnBiomes = ["minecraft:snowy_tundra", "minecraft:snowy_mountains", "minecraft:snowy_taiga", "minecraft:snowy_taiga_hills", "minecraft:snowy_taiga_mountains", "byg:snowy_deciduous_forest", "byg:snowy_blue_taiga", "byg:snowy_evergreen_taiga", "byg:snowy_coniferous_forest", "byg:zelkova_clearing", "byg:cherry_blossom_forest"]
		#Weight of entity in spawn
		#Range: > 0
		entityWeight = 18

	[entities.cluckshroom]
		#Minimum number of entities in group
		#Range: > 0
		entityGroupMin = 2
		#Maximum number of entities in group
		#Range: > 0
		entityGroupMax = 3
		#Biome where entity Spawn
		spawnBiomes = ["minecraft:mushroom_fields", "minecraft:mushroom_fields", "byg:fungal_patch", "byg:tropical_fungal_forest", "byg:tropical_fungal_rainforest_hills", "byg:glowshroom_bayou"]
		#Weight of entity in spawn
		#Range: > 0
		entityWeight = 10

	[entities.rockySheep]
		#Minimum number of entities in group
		#Range: > 0
		entityGroupMin = 2
		#Maximum number of entities in group
		#Range: > 0
		entityGroupMax = 3
		#Biome where entity Spawn
		spawnBiomes = ["minecraft:mountains", "minecraft:wooded_mountains", "minecraft:gravelly_mountains", "minecraft:modified_gravelly_mountains", "byg:dover_mountains", "byg:wooded_grassland_plateau"]
		#Weight of entity in spawn
		#Range: > 0
		entityWeight = 10

	[entities.hornedSheep]
		#Minimum number of entities in group
		#Range: > 0
		entityGroupMin = 2
		#Maximum number of entities in group
		#Range: > 0
		entityGroupMax = 3
		#Biome where entity Spawn
		spawnBiomes = ["minecraft:mountains", "minecraft:wooded_mountains", "byg:alps", "byg:bluff_peaks", "byg:bluff_steeps", "byg:grassland_plateau", "byg:guiana_clearing", "byg:redwood_mountains"]
		#Weight of entity in spawn
		#Range: > 0
		entityWeight = 10

	[entities.spottedPig]
		#Minimum number of entities in group
		#Range: > 0
		entityGroupMin = 2
		#Maximum number of entities in group
		#Range: > 0
		entityGroupMax = 3
		#Biome where entity Spawn
		spawnBiomes = ["minecraft:jungle", "minecraft:swamp", "minecraft:swamp_hills", "byg:bog", "byg:cold_swamplands", "byg:forest_fault"]
		#Weight of entity in spawn
		#Range: > 0
		entityWeight = 10

	[entities.tropicalSlime]
		#Minimum number of entities in group
		#Range: > 0
		entityGroupMin = 1
		#Maximum number of entities in group
		#Range: > 0
		entityGroupMax = 1
		#Biome where entity Spawn
		spawnBiomes = ["minecraft:beach", "byg:rainbow_beach", "byg:oasis", "byg:white_beach", "byg:crag_gardens"]
		#Weight of entity in spawn
		#Range: > 0
		entityWeight = 10

	[entities.skeletonWolf]
		#Minimum number of entities in group
		#Range: > 0
		entityGroupMin = 2
		#Maximum number of entities in group
		#Range: > 0
		entityGroupMax = 3
		#Biome where entity Spawn
		spawnBiomes = ["byg:prairie", "minecraft:taiga", "minecraft:taiga_hills", "minecraft:taiga_mountains", "minecraft:snowy_taiga", "minecraft:snowy_taiga_hills", "minecraft:snowy_taiga_mountains", "minecraft:giant_tree_taiga", "minecraft:giant_tree_taiga_hills", "minecraft:giant_spruce_taiga", "minecraft:giant_spruce_taiga_hills", "minecraft:badlands", "minecraft:badlands_plateau", "minecraft:modified_badlands_plateau", "minecraft:wooded_badlands_plateau", "minecraft:modified_wooded_badlands_plateau", "minecraft:eroded_badlands", "byg:blue_taiga", "byg:blue_taiga_hills", "byg:blue_giant_taiga", "byg:evergreen_taiga", "byg:coniferous_forest", "byg:maple_taiga", "byg:black_forest_hills", "byg:guiana_shield", "byg:shattered_glacier"]
		#Weight of entity in spawn
		#Range: > 0
		entityWeight = 8

	[entities.vestedRabbit]
		#Minimum number of entities in group
		#Range: > 0
		entityGroupMin = 2
		#Maximum number of entities in group
		#Range: > 0
		entityGroupMax = 3
		#Biome where entity Spawn
		spawnBiomes = ["minecraft:mountains", "minecraft:wooded_mountains", "byg:alps", "byg:aspen_clearing", "byg:aspen_forest", "byg:orchard", "byg:coniferous_forest", "byg:maple_taiga", "byg:boreal_clearing"]
		#Weight of entity in spawn
		#Range: > 0
		entityWeight = 4

