
#Mob settings
[mobs]
	#Spawn weight for wraith entity. Set to zero to disable spawning.
	#Range: 0 ~ 1000
	wraithSpawnWeight = 30
	#Spawn weight for zombie brute entity. Set to zero to disable spawning.
	#Range: 0 ~ 1000
	zombieBruteSpawnWeight = 25

#World generation settings
[world]
	#Whether lead ore is enabled. Set to false to disable spawning.
	leadEnabled = true
	#Minimum Y value for lead ore veins
	#Range: 0 ~ 254
	leadOreMinY = 16
	#Maximum Y value for lead ore veins
	#Range: 1 ~ 255
	leadOreMaxY = 32
	#Maximum number of blocks per lead ore vein
	#Range: 1 ~ 255
	leadOreVeinSize = 4
	#Number of lead ore veins per chunk
	#Range: 0 ~ 255
	leadOreVeinCount = 5
	#Whether the lab structure is enabled. Set to false to disable spawning.
	labEnabled = true
	#Rarity of the lab structure. Higher numbers mean rarer structures.
	#Range: 1.0 ~ 1000.0
	labRarity = 25.0
	#Whether the stray tower structure is enabled. Set to false to disable spawning.
	strayTowerEnabled = true
	#Rarity of the stray tower structure. Higher numbers mean rarer structures.
	#Range: 1.0 ~ 1000.0
	strayTowerRarity = 8.0
	#Whether the catacomb structure is enabled. Set to false to disable spawning.
	catacombEnabled = true
	#Rarity of the catacomb structure. Higher numbers mean rarer structures.
	#Range: 1.0 ~ 1000.0
	catacombRarity = 25.0

