
[balance]
	#Crying Obsidian spawn rarity
	#Range: 0 ~ 64
	obsidian_ore_rarity = 6
	#Quartz Ore spawn rarity
	#Range: 0 ~ 64
	quartz_rarity = 2
	#The End new structures
	new_structures_end = true
	#Random model size | If enabled, server logs can spam with warning about enderman spawning
	enderman_tweaks = false
	#End Crypt maximum size
	#Range: 0 ~ 64
	crypt_size = 10
	#End Moss spawn rarity
	#Range: 0 ~ 64
	moss_rarity = 4
	#Dragonite flower spawn rarity
	#Range: 0 ~ 64
	dragonite_rarity = 1
	#Xorcite Spikes spawn rarity
	#Range: 0 ~ 64
	xorcite_spikes_rarity = 3
	#Cracked Purpur and Cracked End Bricks spawn rarity
	#Range: 0 ~ 64
	decorator_rarity = 4
	#Tungsten Ore spawn rarity
	#Range: 0 ~ 64
	tungsten_rarity = 3

