
#Server and Client side changes.
[common]
	#Obsidian Spire rarity (higher number = lower spawnrate)
	obsidianSpireSpawnRate = 6
	#Disables the Looter's ability to take the player's weapon (This makes them spawn with a random weapon, good and bad)
	disableLooterStealing = false
	#Farlander Loot Well rarity (higher number = lower spawnrate)
	farlanderLootWellSpawnRate = 14

	[common.small_house]
		#Spacing between structures
		#Range: > 1
		spacing = 35
		#Offsets the spacing of the structures randomly
		#Range: > 0
		offset = 12
		#Chance of generating in an allowed chunk
		#Range: 0.0 ~ 1.0
		probability = 0.8

	[common.farlander_village]
		#Spacing between structures
		#Range: > 1
		spacing = 42
		#Offsets the spacing of the structures randomly
		#Range: > 0
		offset = 16
		#Chance of generating in an allowed chunk
		#Range: 0.0 ~ 1.0
		probability = 0.7

