
[general]
	#When enabled, attacking a player-built golem will make it attack you
	friendly_fire = true
	#Super secret special days
	holidays = true
	#Percent chance for a villager to successfully summon an Extra Golems golem
	#Range: 0 ~ 100
	villager_summon_chance = 60
	#Golems that can be summoned by villagers
	#(Duplicate entries increase chances)
	villager_summon_golems = ["golems:golem_bookshelf", "golems:golem_clay", "golems:golem_coal", "golems:golem_crafting", "golems:golem_glass", "golems:golem_glowstone", "golems:golem_leaves", "golems:golem_melon", "golems:golem_mushroom", "golems:golem_obsidian", "golems:golem_quartz", "golems:golem_red_sandstone", "golems:golem_sandstone", "golems:golem_stained_glass", "golems:golem_colored_terracotta", "golems:golem_straw", "golems:golem_terracotta", "golems:golem_wooden", "golems:golem_wool"]
	#When true, only players in creative mode can use a Bedrock Golem spawn item
	bedrock_golem_creative_only = true
	#When enabled, players can 'use' the spell item on a carved pumpkin to convert it to a golem head in-world
	use_spell = true
	#When true, pumpkins can be used to build this mod's golems
	pumpkin_builds_golems = false
	#When enabled, some golems will change their texture when clicked
	texture_interact = false
	#When enabled, giving blocks and items to golems can restore health
	heal_golems = true

[golem_granite]
	#Range: 1.0 ~ 999.0
	attack = 5.2
	#Range: 1.0 ~ 999.0
	health = 58.0
	#Disables in-world building of the golem.
	enabled = true

[golem_straw]
	#Range: 1.0 ~ 999.0
	attack = 1.0
	#Range: 1.0 ~ 999.0
	health = 10.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_straw.specials]
		#Whether this golem can speed up crop growth
		"Allow Special: Crop Boost" = true
		#Minimum number of ticks between crop-boosts
		"Crop Boost Frequency" = 460

[golem_tallow]
	#Range: 1.0 ~ 999.0
	attack = 2.0
	#Range: 1.0 ~ 999.0
	health = 48.0
	#Disables in-world building of the golem.
	enabled = true

[golem_nether_brick]
	#Range: 1.0 ~ 999.0
	attack = 6.5
	#Range: 1.0 ~ 999.0
	health = 25.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_nether_brick.specials]
		#Whether this golem can light creatures on fire
		"Allow Special: Burn Enemies" = true

[golem_glass]
	#Range: 1.0 ~ 999.0
	attack = 13.0
	#Range: 1.0 ~ 999.0
	health = 8.0
	#Disables in-world building of the golem.
	enabled = true

[golem_concrete]
	#Range: 1.0 ~ 999.0
	attack = 5.0
	#Range: 1.0 ~ 999.0
	health = 47.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_concrete.specials]
		#Whether this golem reduces damage it takes
		"Allow Special: Resistance" = true

[golem_emerald]
	#Range: 1.0 ~ 999.0
	attack = 18.0
	#Range: 1.0 ~ 999.0
	health = 190.0
	#Disables in-world building of the golem.
	enabled = true

[golem_gold]
	#Range: 1.0 ~ 999.0
	attack = 8.0
	#Range: 1.0 ~ 999.0
	health = 80.0
	#Disables in-world building of the golem.
	enabled = true

[golem_crafting]
	#Range: 1.0 ~ 999.0
	attack = 2.0
	#Range: 1.0 ~ 999.0
	health = 24.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_crafting.specials]
		#Whether this golem can open a crafting grid
		"Allow Special: Crafting" = true

[golem_soul_sandstone]
	#Range: 1.0 ~ 999.0
	attack = 4.0
	#Range: 1.0 ~ 999.0
	health = 30.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_soul_sandstone.specials]
		#Whether this golem can apply slowness when attacking
		"Allow Special: Slowness" = true

[golem_leaves]
	#Range: 1.0 ~ 999.0
	attack = 1.0
	#Range: 1.0 ~ 999.0
	health = 6.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_leaves.specials]
		#Whether this golem can heal itself
		"Allow Special: Regeneration" = true

[golem_purpur]
	#Range: 1.0 ~ 999.0
	attack = 3.0
	#Range: 1.0 ~ 999.0
	health = 82.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_purpur.specials]
		#Whether this golem can teleport
		"Allow Special: Teleporting" = true

[golem_kelp]
	#Range: 1.0 ~ 999.0
	attack = 2.0
	#Range: 1.0 ~ 999.0
	health = 34.0
	#Disables in-world building of the golem.
	enabled = true

[golem_clay]
	#Range: 1.0 ~ 999.0
	attack = 2.0
	#Range: 1.0 ~ 999.0
	health = 20.0
	#Disables in-world building of the golem.
	enabled = true

[golem_nether_wart]
	#Range: 1.0 ~ 999.0
	attack = 1.5
	#Range: 1.0 ~ 999.0
	health = 22.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_nether_wart.specials]
		#Average number of ticks between planting nether wart (if enabled)
		"Netherwart Frequency" = 880
		#Whether this golem can plant netherwart randomly
		"Allow Special: Plant Netherwart" = true
		#Whether this golem can randomly heal (at night)
		"Allow Special: Random Healing" = true

[golem_redstone_lamp]
	#Range: 1.0 ~ 999.0
	attack = 6.0
	#Range: 1.0 ~ 999.0
	health = 28.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_redstone_lamp.specials]
		#Whether this golem can light up the area
		"Allow Special: Emit Light" = true

[golem_elder_sea_lantern]
	#Range: 1.0 ~ 999.0
	attack = 6.1
	#Range: 1.0 ~ 999.0
	health = 36.0
	#Disables in-world building of the golem.
	enabled = true

[golem_quilted_wool]
	#Range: 1.0 ~ 999.0
	attack = 1.0
	#Range: 1.0 ~ 999.0
	health = 16.0
	#Disables in-world building of the golem.
	enabled = true

[golem_redstone]
	#Range: 1.0 ~ 999.0
	attack = 2.0
	#Range: 1.0 ~ 999.0
	health = 18.0
	#Disables in-world building of the golem.
	enabled = true

[golem_basalt]
	#Range: 1.0 ~ 999.0
	attack = 6.8
	#Range: 1.0 ~ 999.0
	health = 58.0
	#Disables in-world building of the golem.
	enabled = true

[golem_honeycomb]
	#Range: 1.0 ~ 999.0
	attack = 2.0
	#Range: 1.0 ~ 999.0
	health = 68.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_honeycomb.specials]
		#Percent chance to summon a bee when attacked [0,100]
		"Summon Bee Chance" = 30

[golem_quartz]
	#Range: 1.0 ~ 999.0
	attack = 8.5
	#Range: 1.0 ~ 999.0
	health = 85.0
	#Disables in-world building of the golem.
	enabled = true

[golem_limestone]
	#Range: 1.0 ~ 999.0
	attack = 5.0
	#Range: 1.0 ~ 999.0
	health = 49.0
	#Disables in-world building of the golem.
	enabled = true

[golem_bedrock]
	#Range: 1.0 ~ 999.0
	attack = 32.0
	#Range: 1.0 ~ 999.0
	health = 999.0
	#Disables in-world building of the golem.
	enabled = true

[golem_glowstone]
	#Range: 1.0 ~ 999.0
	attack = 12.0
	#Range: 1.0 ~ 999.0
	health = 8.0
	#Disables in-world building of the golem.
	enabled = true

[golem_wool]
	#Range: 1.0 ~ 999.0
	attack = 1.0
	#Range: 1.0 ~ 999.0
	health = 10.0
	#Disables in-world building of the golem.
	enabled = true

[golem_furnace]
	#Range: 1.0 ~ 999.0
	attack = 6.5
	#Range: 1.0 ~ 999.0
	health = 88.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_furnace.specials]
		#Number of ticks between using fuel points
		"Burn Time" = 10

[golem_obsidian]
	#Range: 1.0 ~ 999.0
	attack = 18.0
	#Range: 1.0 ~ 999.0
	health = 120.0
	#Disables in-world building of the golem.
	enabled = true

[golem_cave_crystal]
	#Range: 1.0 ~ 999.0
	attack = 8.2
	#Range: 1.0 ~ 999.0
	health = 18.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_cave_crystal.specials]
		#Whether this golem can glow
		"Allow Special: Emit Light" = true

[golem_framed_glass]
	#Range: 1.0 ~ 999.0
	attack = 8.5
	#Range: 1.0 ~ 999.0
	health = 16.0
	#Disables in-world building of the golem.
	enabled = true

[golem_end_stone]
	#Range: 1.0 ~ 999.0
	attack = 8.0
	#Range: 1.0 ~ 999.0
	health = 50.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_end_stone.specials]
		#Whether the Endstone Golem takes damage from water
		"Can Take Water Damage" = true
		#Whether this golem can teleport
		"Allow Special: Teleporting" = true

[golem_bone]
	#Range: 1.0 ~ 999.0
	attack = 9.5
	#Range: 1.0 ~ 999.0
	health = 40.0
	#Disables in-world building of the golem.
	enabled = true

[golem_duskbound]
	#Range: 1.0 ~ 999.0
	attack = 6.6
	#Range: 1.0 ~ 999.0
	health = 84.0
	#Disables in-world building of the golem.
	enabled = true

[golem_sea_lantern]
	#Range: 1.0 ~ 999.0
	attack = 6.0
	#Range: 1.0 ~ 999.0
	health = 34.0
	#Disables in-world building of the golem.
	enabled = true

[golem_andesite]
	#Range: 1.0 ~ 999.0
	attack = 6.0
	#Range: 1.0 ~ 999.0
	health = 52.0
	#Disables in-world building of the golem.
	enabled = true

[golem_textured]
	#Range: 1.0 ~ 999.0
	attack = 6.0
	#Range: 1.0 ~ 999.0
	health = 76.0
	#Disables in-world building of the golem.
	enabled = true

[golem_tnt]
	#Range: 1.0 ~ 999.0
	attack = 2.5
	#Range: 1.0 ~ 999.0
	health = 14.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_tnt.specials]
		#Whether this golem can explode when fighting or dying
		"Allow Special: Explode" = true

[golem_coal]
	#Range: 1.0 ~ 999.0
	attack = 2.5
	#Range: 1.0 ~ 999.0
	health = 24.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_coal.specials]
		#Whether this golem can inflict blindness
		"Allow Special: Blindness" = false

[golem_bookshelf]
	#Range: 1.0 ~ 999.0
	attack = 1.5
	#Range: 1.0 ~ 999.0
	health = 28.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_bookshelf.specials]
		#Whether this golem can give itself potion effects
		"Allow Special: Potion Effects" = true

[golem_glowshroom]
	#Range: 1.0 ~ 999.0
	attack = 3.0
	#Range: 1.0 ~ 999.0
	health = 30.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_glowshroom.specials]
		#Whether this golem can glow
		"Allow Special: Emit Light" = true
		#Whether this golem can plant glowshrooms randomly
		"Allow Special: Plant Glowshrooms" = true
		#Whether this golem can randomly heal (at night)
		"Allow Special: Random Healing" = true
		#Average number of ticks between planting glowshrooms
		"Mushroom Frequency" = 420

[golem_duskbound_lamp]
	#Range: 1.0 ~ 999.0
	attack = 6.0
	#Range: 1.0 ~ 999.0
	health = 88.0
	#Disables in-world building of the golem.
	enabled = true

[golem_lapis]
	#Range: 1.0 ~ 999.0
	attack = 1.5
	#Range: 1.0 ~ 999.0
	health = 50.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_lapis.specials]
		#Whether this golem can inflict harmful potion effects
		"Allow Special: Potion Effects" = true

[golem_jasper]
	#Range: 1.0 ~ 999.0
	attack = 5.9
	#Range: 1.0 ~ 999.0
	health = 52.0
	#Disables in-world building of the golem.
	enabled = true

[golem_iron_plate]
	#Range: 1.0 ~ 999.0
	attack = 7.0
	#Range: 1.0 ~ 999.0
	health = 40.0
	#Disables in-world building of the golem.
	enabled = true

[golem_prismarine]
	#Range: 1.0 ~ 999.0
	attack = 8.0
	#Range: 1.0 ~ 999.0
	health = 34.0
	#Disables in-world building of the golem.
	enabled = true

[golem_honey]
	#Range: 1.0 ~ 999.0
	attack = 1.0
	#Range: 1.0 ~ 999.0
	health = 42.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_honey.specials]
		#Whether this golem applies honey effect to mobs
		"Allow Special: Honey" = true
		#The number of mini-golems to spawn when this golem dies
		"Splitting Factor" = 2

[golem_sponge]
	#Range: 1.0 ~ 999.0
	attack = 1.5
	#Range: 1.0 ~ 999.0
	health = 20.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_sponge.specials]
		#Number of ticks between each water-check; increase to reduce lag
		"Water Soaking Frequency" = 10
		#Whether this golem can absorb water
		"Allow Special: Absorb Water" = true
		#Radial distance at which this golem can absorb water (Warning: larger values cause lag)
		"Water Soaking Range" = 5

[golem_stained_glass]
	#Range: 1.0 ~ 999.0
	attack = 12.0
	#Range: 1.0 ~ 999.0
	health = 9.0
	#Disables in-world building of the golem.
	enabled = true

[golem_slate]
	#Range: 1.0 ~ 999.0
	attack = 5.8
	#Range: 1.0 ~ 999.0
	health = 50.0
	#Disables in-world building of the golem.
	enabled = true

[golem_midori]
	#Range: 1.0 ~ 999.0
	attack = 3.0
	#Range: 1.0 ~ 999.0
	health = 32.0
	#Disables in-world building of the golem.
	enabled = true

[golem_permafrost]
	#Range: 1.0 ~ 999.0
	attack = 4.0
	#Range: 1.0 ~ 999.0
	health = 42.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_permafrost.specials]
		#Whether this golem can apply slowness when attacking
		"Allow Special: Slowness" = true

[golem_shroomlight]
	#Range: 1.0 ~ 999.0
	attack = 3.0
	#Range: 1.0 ~ 999.0
	health = 40.0
	#Disables in-world building of the golem.
	enabled = true

[golem_wooden]
	#Range: 1.0 ~ 999.0
	attack = 3.0
	#Range: 1.0 ~ 999.0
	health = 20.0
	#Disables in-world building of the golem.
	enabled = true

[golem_colored_terracotta]
	#Range: 1.0 ~ 999.0
	attack = 4.0
	#Range: 1.0 ~ 999.0
	health = 42.0
	#Disables in-world building of the golem.
	enabled = true

[golem_brimstone]
	#Range: 1.0 ~ 999.0
	attack = 6.5
	#Range: 1.0 ~ 999.0
	health = 25.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_brimstone.specials]
		#Whether this golem can light creatures on fire
		"Allow Special: Burn Enemies" = true

[golem_diamond]
	#Range: 1.0 ~ 999.0
	attack = 20.0
	#Range: 1.0 ~ 999.0
	health = 220.0
	#Disables in-world building of the golem.
	enabled = true

[golem_netherite]
	#Range: 1.0 ~ 999.0
	attack = 28.0
	#Range: 1.0 ~ 999.0
	health = 298.0
	#Disables in-world building of the golem.
	enabled = true

[golem_blaze_lantern]
	#Range: 1.0 ~ 999.0
	attack = 7.6
	#Range: 1.0 ~ 999.0
	health = 34.0
	#Disables in-world building of the golem.
	enabled = true

[golem_red_sandstone]
	#Range: 1.0 ~ 999.0
	attack = 4.0
	#Range: 1.0 ~ 999.0
	health = 22.0
	#Disables in-world building of the golem.
	enabled = true

[golem_slime]
	#Range: 1.0 ~ 999.0
	attack = 2.5
	#Range: 1.0 ~ 999.0
	health = 58.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_slime.specials]
		#Slime Golem knockback power (Higher Value = Further Knockback)
		"Knockback Factor" = 1.0412
		#Whether this golem can apply extra knockback when attacking
		"Allow Special: Extra Knockback" = true
		#The number of mini-golems to spawn when this golem dies
		"Splitting Factor" = 2

[golem_sturdy_stone]
	#Range: 1.0 ~ 999.0
	attack = 4.0
	#Range: 1.0 ~ 999.0
	health = 70.0
	#Disables in-world building of the golem.
	enabled = true

[golem_crimson_stem]
	#Range: 1.0 ~ 999.0
	attack = 3.0
	#Range: 1.0 ~ 999.0
	health = 24.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_crimson_stem.specials]
		#Whether this golem can plant crimson fungus
		"Allow Special: Plant Fungus" = true
		#Average number of ticks between planting fungus
		"Fungus Frequency" = 420

[golem_crying_obsidian]
	#Range: 1.0 ~ 999.0
	attack = 18.9
	#Range: 1.0 ~ 999.0
	health = 106.0
	#Disables in-world building of the golem.
	enabled = true

[golem_melon]
	#Range: 1.0 ~ 999.0
	attack = 1.5
	#Range: 1.0 ~ 999.0
	health = 18.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_melon.specials]
		#Average number of ticks between planting flowers
		"Flower Frequency" = 240
		#Whether this golem can plant flowers randomly
		"Allow Special: Plant Flowers" = true
		#Whether this golem can occasionally heal
		"Allow Special: Random Healing" = true

[golem_color_slime]
	#Range: 1.0 ~ 999.0
	attack = 2.5
	#Range: 1.0 ~ 999.0
	health = 58.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_color_slime.specials]
		#Slime Golem knockback power (Higher Value = Further Knockback)
		"Knockback Factor" = 1.0412
		#Whether this golem can apply extra knockback when attacking
		"Allow Special: Extra Knockback" = true
		#The number of mini-golems to spawn when this golem dies
		"Splitting Factor" = 2

[golem_marble]
	#Range: 1.0 ~ 999.0
	attack = 6.5
	#Range: 1.0 ~ 999.0
	health = 54.0
	#Disables in-world building of the golem.
	enabled = true

[golem_sandstone]
	#Range: 1.0 ~ 999.0
	attack = 4.0
	#Range: 1.0 ~ 999.0
	health = 22.0
	#Disables in-world building of the golem.
	enabled = true

[golem_ice]
	#Range: 1.0 ~ 999.0
	attack = 6.0
	#Range: 1.0 ~ 999.0
	health = 18.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_ice.specials]
		#When true, this golem places frosted (temporary) ice
		"Use Frosted Ice" = false
		#Radial distance at which this golem can freeze / cool liquids (0=disable)
		"Area of Effect" = 3

[golem_blackstone]
	#Range: 1.0 ~ 999.0
	attack = 6.8
	#Range: 1.0 ~ 999.0
	health = 58.0
	#Disables in-world building of the golem.
	enabled = true

[golem_warped_stem]
	#Range: 1.0 ~ 999.0
	attack = 3.0
	#Range: 1.0 ~ 999.0
	health = 24.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_warped_stem.specials]
		#Whether this golem can plant warped fungus
		"Allow Special: Plant Fungus" = true
		#Average number of ticks between planting fungus
		"Fungus Frequency" = 420

[golem_mushroom]
	#Range: 1.0 ~ 999.0
	attack = 3.0
	#Range: 1.0 ~ 999.0
	health = 30.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_mushroom.specials]
		#Whether this golem can plant mushrooms randomly
		"Allow Special: Plant Mushrooms" = true
		#Whether this golem can randomly heal (at night)
		"Allow Special: Random Healing" = true
		#Average number of ticks between planting mushrooms
		"Mushroom Frequency" = 420

[golem_terracotta]
	#Range: 1.0 ~ 999.0
	attack = 4.0
	#Range: 1.0 ~ 999.0
	health = 42.0
	#Disables in-world building of the golem.
	enabled = true

[golem_biotite]
	#Range: 1.0 ~ 999.0
	attack = 8.5
	#Range: 1.0 ~ 999.0
	health = 116.0
	#Disables in-world building of the golem.
	enabled = true

[golem_smooth_stone]
	#Range: 1.0 ~ 999.0
	attack = 5.4
	#Range: 1.0 ~ 999.0
	health = 60.0
	#Disables in-world building of the golem.
	enabled = true

[golem_charcoal]
	#Range: 1.0 ~ 999.0
	attack = 2.5
	#Range: 1.0 ~ 999.0
	health = 24.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_charcoal.specials]
		#Whether this golem can inflict blindness
		"Allow Special: Blindness" = false

[golem_diorite]
	#Range: 1.0 ~ 999.0
	attack = 6.0
	#Range: 1.0 ~ 999.0
	health = 50.0
	#Disables in-world building of the golem.
	enabled = true

[golem_dispenser]
	#Range: 1.0 ~ 999.0
	attack = 7.0
	#Range: 1.0 ~ 999.0
	health = 68.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_dispenser.specials]
		#Number of ticks between shooting arrows
		"Arrow Speed" = 28
		#Whether the golem can shoot arrows
		"Allow Special: Shoot Arrows" = true
		#Base amount of damage dealt per arrow
		"Arrow Damage" = 4.25

[golem_elder_prismarine]
	#Range: 1.0 ~ 999.0
	attack = 7.0
	#Range: 1.0 ~ 999.0
	health = 38.0
	#Disables in-world building of the golem.
	enabled = true

[golem_magma]
	#Range: 1.0 ~ 999.0
	attack = 4.5
	#Range: 1.0 ~ 999.0
	health = 46.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_magma.specials]
		#When true, water will hurt this golem
		"Enable Water Damage" = true
		#Whether this golem can light creatures on fire
		"Allow Special: Burn Enemies" = true
		#Whether this golem can slowly melt cobblestone
		"Allow Special: Melt Cobblestone" = false
		#Number of ticks it takes to melt cobblestone if enabled (12 sec * 20 t/sec = 240 t)
		"Melting Delay" = 240
		#The number of mini-golems to spawn when this golem dies
		"Splitting Factor" = 2

[golem_coral]
	#Range: 1.0 ~ 999.0
	attack = 6.0
	#Range: 1.0 ~ 999.0
	health = 38.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_coral.specials]
		#Number of ticks golem can stay out of water before drying out
		"Max Wet Time" = 425
		#Whether this golem can occasionally heal when wet
		"Allow Special: Healing" = true

