
#Biome config
#To filter biomes by registry name "mod_id:biome_id"
#To filter biomes by category "@category"
#To filter biomes by tags "#tag"
#	Examples:
#		"minecraft:plains"
#		"@desert"
#		"#overworld"
#
#If you want to exclude biomes put a ! before the biome identifier
#	Examples:
#		"!minecraft:plains"
#		"!@desert"
#		"!#nether"
#
#If you want to include biomes that would be satisfied by any in a set use |
#	Examples:
#		"|minecraft:plains"
#		"|@desert"
#		"|#nether"
#
#If you want a condition that MUST be satisfied use an & before the biome identifier
#Please note using this on a registry name wouldn't be that useful
#	Examples:
#		"&minecraft:plains"
#		"&@forest"
#		"&#overworld"
#
#NOTE: Any entry without a !, |, or & symbol has a higher precedence
#A list like ["!minecraft:plains", "#overworld"] would still see the plains as a viable biome
#
#Finally, you can create a expression that can be evaluated by itself using a + to combine identifiers
#	Examples:
#		"!#hot+!#dry+!#mountain"
#
#These expressions can be used to filter biomes in a lot of ways
#Lets say we don't want anything to spawn in any place dry and sandy
#	"!#dry+!#sandy"
#
#But there is a hot place we want them to spawn that's also wet
#	"#hot+#wet"
#
#We just put them as separate values in the list and that'll work out
#	["!#dry+!#sandy","#hot+#wet"]
#
#NOTE: Any entry that's an expression will not be affected by anything else in the list
[biome_configs]
	deathwormBiomes = ["&#overworld+|@desert+|byg:sierra_valley+|byg:red_rock_lowlands", "|gaiadimension:salt_dunes+|byg:shattered_desert"]
	lightningDragonBiomes = ["&#overworld+|#jungle+|#mountain+!#cold+|byg:jacaranda_forest+|byg:jacaranda_forest_hills+|byg:jacaranda_clearing", "|gaiadimension:static_wasteland"]
	cockatriceBiomes = ["&#overworld+|@savanna+|#savanna+|byg:shrublands+|byg:mojave_desert"]
	blackHippogryphBiomes = ["|byg:ebony_woods+|byg:ebony_hills+|byg:the_black_forest+|byg:black_forest_hills+|byg:black_forest_clearing+|byg:basalt_barrera+|byg:twilight_valley+|byg:twilight_valley_hills"]
	lightningLilyBiomes = ["&#overworld+|#jungle", "|gaiadimension:static_wasteland"]
	sirenBiomes = ["|minecraft:lukewarm_ocean+|minecraft:warm_ocean+|minecraft:deep_warm_ocean+|minecraft:deep_lukewarm_ocean"]
	amphithereBiomes = ["&#overworld+|#jungle", "|rats:ratlantis_biome+|gaiadimension:green_agate_jungle"]
	fireDragonSkeletonBiomes = ["&#overworld+|@desert"]
	brownHippogryphBiomes = ["&#overworld+|#mountain+|@extreme_hills"]
	amethystBiomes = ["&#overworld+|@savanna+|#savanna+|byg:rainbow_beach", "|jellyfishing:jellyfish_fields", "|gaiadimension:purple_agate_swamp"]
	hippocampusBiomes = ["|minecraft:deep_lukewarm_ocean+|minecraft:lukewarm_ocean"]
	snowyTrollBiomes = ["&#overworld+|#snowy+|#cold"]
	hippogryphBiomes = ["&#overworld+|#mesa+|#mountain+|#hills+|@extreme_hills"]
	iceDragonSkeletonBiomes = ["&#overworld+&#snowy+|@icy+|#cold", "|byg:subzero_hypogeal"]
	jungleMyrmexBiomes = ["&#overworld+|#jungle", "|rats:ratlantis_biome+|gaiadimension:green_agate_jungle"]
	mausoleumBiomes = ["&#overworld+&#snowy+|@icy+|#cold"]
	sapphireBiomes = ["&#overworld+&#snowy+|@icy+|#cold+|byg:rainbow_beach", "|gaiadimension:blue_agate_taiga"]
	mountainTrollBiomes = ["&#overworld+|#mountain+|@extreme_hills", "|mining_dimension:mining"]
	iceLilyBiomes = ["&#overworld+&#snowy+|@icy+|#cold", "|byg:subzero_hypogeal"]
	chestnutHippogryphBiomes = ["|minecraft:wooded_mountains+|byg:cika_mountains+|byg:weeping_witch_forest+|byg:weeping_witch_clearing+|byg:wooded_grassland_plateau+|byg:pumpkin_forest"]
	pixieBiomes = ["&#overworld+|#magical+|#dense+&#forest+!@taiga+!#hills+!#mountain+!#wet+!#hot+!#cold+!#dry", "|gaiadimension:pink_agate_forest"]
	creamyHippogryphBiomes = ["&#overworld+|@savanna+|#savanna"]
	overworldSpawnBiomes = ["|#overworld"]
	forestTrollBiomes = ["&#overworld+|@forest+|#forest"]
	grayHippogryphBiomes = ["|byg:stone_forest+|byg:pointed_stone_forest+|byg:dead_sea"]
	seaSerpentBiomes = ["|minecraft:deep_cold_ocean+|minecraft:deep_frozen_ocean+|minecraft:deep_lukewarm_ocean+|minecraft:deep_ocean+|minecraft:deep_warm_ocean"]
	cyclopsCaveBiomes = ["|byg:rocky_beach+|minecraft:stone_shore+|byg:snowy_black_beach+|byg:snowy_rocky_black_beach"]
	stymphalianBiomes = ["&#overworld+|@swamp+|#swamp", "|gaiadimension:purple_agate_swamp"]
	gorgonTempleBiomes = ["&#overworld+|@beach+!byg:rocky_beach+!minecraft:stone_shore+!byg:snowy_black_beach+!byg:snowy_rocky_black_beach|#beach+!byg:rocky_beach+!minecraft:stone_shore+!byg:snowy_black_beach+!byg:snowy_rocky_black_beach"]
	hydraBiomes = ["&#overworld+|@swamp+|#swamp", "|undergarden:mushroom_bog"]
	whiteHippogryphBiomes = ["&#overworld+|#mountain+|#snowy"]
	fireLilyBiomes = ["&#overworld+|#hot+!#water", "|byg:cryptic_wastes+|byg:magma_wastes"]
	graveyardBiomes = ["&#overworld+!@ocean+!#ocean+!#water+!@beach+!#beach+!@mushroom+!#mushroom"]
	oreGenBiomes = ["|#overworld"]
	iceDragonBiomes = ["&#overworld+|@icy+|#snowy+!#beach+!#water+|#cold+!#beach+!#water", "|byg:subzero_hypogeal"]
	darkBrownHippogryphBiomes = ["&#overworld+|@taiga"]
	wanderingCyclopsBiomes = ["&#overworld+|@plains+|#plains"]
	desertMyrmexBiomes = ["&#overworld+|@desert+|#sandy+!#beach+!#water"]
	lightningDragonSkeletonBiomes = ["&#overworld+|#mountain+!#cold+|#wet+!#cold+!#water+!#ocean+!river+!byg:bayou+!byg:cypress_swamplands+!byg:mangrove_marshes+!byg:coral_mangroves"]
	fireDragonBiomes = ["&#overworld+|#hot+#mesa+#mountain+#sparse+#plateau+!@desert+!@savanna+!#savanna+!#wet+!#cold+!#forest+!#jungle+!#water+!#ocean+!#river", "|gaiadimension:volcanic_lands+|good_nights_sleep:wasted_forest"]

