
[General]
	#Biome Weight of Jellyfish Fields
	#Range: 1 ~ 100
	jellyfish_fields_weight = 4
	#Should Jellyfish be fishable with a fishing rod?
	jellyfish_fishable = true
	#Should Jellyfish Nets be fishable with a fishing rod?
	nets_fishable = true
	#Should Jellyfish sting?
	jellyfish_sting = true

