
[General]
	#Should Presents only spawn in snowy biomes?
	only_in_snowy_biomes = false
	#Minimum amount of presents that can spawn
	#Range: 0 ~ 32
	present_minimum = 2
	#Maximum amount of presents that can spawn
	#Range: 0 ~ 32
	present_maximum = 3
	#Chance of Jolly Boxes to spawn when you sleep (Set to 0 to disable spawning)
	#Range: 0.0 ~ 1.0
	present_chance = 0.5
	#Should Presents only spawn during December?
	only_in_december = false

