
[Misc]
	#Stack Size
	#Range: 1 ~ 64
	stacksize = 1
	#How many items drop when a loot bag is used
	#Range: 1 ~ 1000
	dropamount = 3
	#Enable debug mode
	debugmode = false

["Mob Drops"]
	#Mob drops list (Syntax " mob name ")
	mobdropslist = ["minecraft:elder_guardian", "minecraft:evoker", "minecraft:illusioner", "doomweapon:arachnotron", "doomweapon:archvile", "doomweapon:baron", "doomweapon:cacodemon", "doomweapon:cyberdemon", "doomweapon:cyberdemon2016", "doomweapon:hellknight", "doomweapon:iconofsin", "doomweapon:imp", "doomweapon:imp2016", "doomweapon:lost_soul", "doomweapon:mancubus", "doomweapon:marauder", "doomweapon:nightmare_imp", "doomweapon:painelemental", "doomweapon:pinky", "doomweapon:revenant", "doomweapon:shotgunguy", "doomweapon:spiderdemon", "doomweapon:unwilling", "doomweapon:zombieman", "good_nights_sleep:herobrine", "good_nights_sleep:tormenter", "hunterillager:hunterillager", "iceandfire:amphithere", "iceandfire:cockatrice", "iceandfire:cyclops", "iceandfire:deathworm", "iceandfire:dread_beast", "iceandfire:dread_ghoul", "iceandfire:dread_knight", "iceandfire:dread_lich", "iceandfire:dread_scuttler", "iceandfire:fire_dragon", "iceandfire:gorgon", "iceandfire:hydra", "iceandfire:ice_dragon", "iceandfire:lightning_dragon", "iceandfire:myrmex_queen", "iceandfire:myrmex_royal", "iceandfire:myrmex_sentinel", "iceandfire:myrmex_soldier", "iceandfire:sea_serpent", "iceandfire:siren", "iceandfire:stymphalian_bird", "iceandfire:troll", "minecraft:ender_dragon", "minecraft:ravager", "minecraft:piglin_brute", "minecraft:vex", "minecraft:wither", "minecraft:zombie_villager", "mutantbeasts:mutant_creeper", "mutantbeasts:mutant_enderman", "mutantbeasts:mutant_skeleton", "mutantbeasts:mutant_zombie", "rats:black_death", "rats:dutchrat", "rats:pied_piper", "rats:plague_beast", "rats:rat_baron", "rats:feral_ratlantean", "rats:rat_king", "rats:ratlantean_automaton", "conjurer_illager:conjurer", "enchantwithmob:enchanter", "farlanders:ender_golem", "farlanders:mystic_enderman", "farlanders:titan", "riskofrainmod:stone_golem", "undergarden:stoneborn", "undergarden:rotbeast", "undergarden:brute", "weeping_angels:weeping_angel", "yeeter:tnt_yeeter", "ice_ice_baby:iceologer", "magma_monsters:magma_monster"]
	#Loot Bag drop chance from mobs (the higher the number the more common they are)
	#Range: 1 ~ 100
	dropchance = 10

["Black And White Lists"]
	#Use the whitelist
	enablewhitelist = true
	#BlackList (Syntax "minecraft or modid : item or block name"; example "minecraft:air" or "lootbagmod:lootbag")
	blacklist = ["minecraft:air", "minecraft:command_block", "minecraft:structure_block", "minecraft:knowledge_book", "minecraft:chain_command_block", "minecraft:repeating_command_block", "minecraft:barrier", "minecraft:enchanted_book", "minecraft:written_book", "minecraft:potion", "minecraft:splash_potion", "minecraft:lingering_potion", "minecraft:spawn_egg", "minecraft:structure_void", "minecraft:mob_spawner", "minecraft:bedrock", "vm:vending_machine", "minecraft:end_portal_frame", "minecraft:command_block_minecart", "quarryplus:quarry_pickaxe"]
	#Mod blacklist (Syntax " modid ")
	modblacklist = ["tconstruct"]
	#WhiteList Syntax "minecraft or modid : item or block name"; example minecraft:air or lootbagmod:lootbag)
	whitelist = ["minecraft:emerald"]
	#TagList (Syntax "minecraft, forge or modid : tag name"; example "minecraft:planks" or "forge:planks")
	taglist = ["curios:curio", "ringsofascension:rings", "curios:statue", "tihi:loot"]

