
#General configuration settings
[General]
	#Valid modes:0: Only chop blocks with the same blockid1: Chop all wooden blocks
	#Range: 0 ~ 1
	mode = 0
	#Hard limit of the amount that can be broken in one go.
	#Range: > 1
	tickLimit = 32
	#Hard limit of the amount that can be broken in one go.
	#Range: > 1
	totalLimit = 1024
	#Harvest leaves too.
	leaves = false
	#Multiplier used for attack speed. Tool material * this value = axe speed
	#Range: -2.147483648E9 ~ 0.0
	damageMultiplier = -5.0

