
#Tool/Armor Material Modifiers
[material_modifiers]
	#Modifies material base damage by this amount [1.0-50.0, default: 8.0]
	#Range: 0.0 ~ 50.0
	attack_damage_modifier = 1.0
	#Modifies material base durability by this amount [1-5, default: 2031]
	#Range: 0 ~ 5
	durability_modifier = 1
	#Modifies material base damage reduction used by armors by this amount [1-5, default: 1]
	#Range: 0 ~ 5
	damage_reduction_modifier = 1

#Opal Ore Generation
[opal_ore]
	#Generate Opal Ore in the world [true / false]
	opalOreGeneration = true
	#Size of Opal Ore pockets [0-100, default: 2]
	#Range: 1 ~ 100
	opalOreSize = 2
	#Maximal height for Opal Ore pocket generation [0-255, default: 22]
	#Range: 0 ~ 255
	opalOreMaxHeight = 13
	#Chances of Opal Ore pocket being generated [0-100, default: 5]
	#Range: 0 ~ 100
	opalOreChance = 3
	#Minimal height for Opal Ore pocket generation, [0-255, default: 8]
	#Range: 0 ~ 255
	opalOreMinHeight = 1

