#Minimum number of potion effects on a common item
#Range: 0 ~ 5
commonPotionMin = 0
#Maximum number of potion effects on a common item
#Range: 0 ~ 5
commonPotionMax = 1
#Minimum number of effects on a common item
#Range: 0 ~ 4
commonEffectMin = 0
#Maximum number of effects on a common item
#Range: 0 ~ 4
commonEffectMax = 0
#Minimum number of potion effects on a uncommon item
#Range: 0 ~ 5
uncommonPotionMin = 0
#Maximum number of potion effects on a uncommon item
#Range: 0 ~ 5
uncommonPotionMax = 4
#Minimum number of effects on a uncommon item
#Range: 0 ~ 4
uncommonEffectMin = 0
#Maximum number of effects on a uncommon item
#Range: 2 ~ 4
uncommonEffectMax = 2
#Minimum number of potion effects on a rare item
#Range: 0 ~ 5
rarePotionMin = 1
#Maximum number of potion effects on a rare item
#Range: 0 ~ 5
rarePotionMax = 4
#Minimum number of effects on a rare item
#Range: 0 ~ 4
rareEffectMin = 1
#Maximum number of effects on a rare item
#Range: 0 ~ 4
rareEffectMax = 2
#Minimum number of potion effects on a epic item
#Range: 0 ~ 5
epicPotionMin = 1
#Maximum number of potion effects on a epic item
#Range: 0 ~ 5
epicPotionMax = 4
#Minimum number of effects on a epic item
#Range: 0 ~ 4
epicEffectMin = 2
#Maximum number of effects on a epic item
#Range: 0 ~ 4
epicEffectMax = 3
#Minimum number of potion effects on a unique item
#Range: 0 ~ 5
uniquePotionMin = 3
#Maximum number of potion effects on a unique item
#Range: 0 ~ 5
uniquePotionMax = 5
#Minimum number of effects on a unique item
#Range: 0 ~ 4
uniqueEffectMin = 3
#Maximum number of effects on a unique item
#Range: 0 ~ 4
uniqueEffectMax = 4
#The chance that the lootcrate loot table will be injected into a chest loot table
#Range: 1 ~ 400
lootCrateWeight = 1
#The minimum number of rolls a loot crate will try to generate, each roll has a 30% chance of generating a loot crate
#Range: 0 ~ 300
lootCrateMinRolls = 0
#the maximum number of rolls a loot crate will try to generate, each roll has a 30% chance of generating a loot crate
#Range: 0 ~ 300
lootCrateMaxRolls = 1
#enable wither effect on tools
enableWither = true
#enable slowness effect on tools
enableSlowness = true
#enable poison effect on tools
enablePoison = true
#enable weakness effect on tools
enableWeakness = true
#enable blindness effect on tools
enableBlindness = true
#enable regeneration effect on tools
enableRegeneration = true
#enable speed effect on tools
enableSpeed = true
#enable haste effect on tools
enableHaste = true
#enable resistance effect on tools
enableResistance = true
#enable fire resistance effect on tools
enableFireResistance = true
#enables mobs dropping crates
enableMobDropCrate = true
#chance that a loot crate will generate a common item
#Range: 0 ~ 100
commonRarity = 50
#chance that a loot crate will generate a uncommon item
#Range: 0 ~ 100
uncommonRarity = 20
#chance that a loot crate will generate a rare item
#Range: 0 ~ 100
rareRarity = 12
#chance that a loot crate will generate a epic item
#Range: 0 ~ 100
epicRarity = 10
#chance that a loot crate will generate a unique item
#Range: 0 ~ 100
uniqueRarity = 8

