
#General configuration options.
[General]
	#The amount of Dragon Scales that an Ender Dragon will drop when killed.
	#Range: 0 ~ 64
	dragonScalesAmount = 8
	#The duration of each Essence Apples effects in seconds.
	#Range: > 1
	essenceAppleDuration = 180
	#Can tier 6 crops be fertilized using Mystical Fertilizer or Fertilized Essence?
	fertilizableTier6Crops = false
	#The percentage chance that a Wither will drop a Withering Soul when killed.
	#Range: 0.0 ~ 1.0
	witheringSoulChance = 0.25

#World generation options.
[World]
	#How many Nether Inferium Ore veins should spawn in a chunk.
	#Range: > 0
	netherInferiumSpawnRate = 2
	#The maximum amount of Nether Inferium Ore blocks that can spawn in a vein.
	#Range: > 0
	netherInferiumSpawnSize = 3
	#How many End Inferium Ore veins should spawn in a chunk.
	#Range: > 0
	endInferiumSpawnRate = 3
	#The maximum Y level that Nether Inferium Ore veins can spawn.
	#Range: 0 ~ 128
	netherInferiumSpawnHeight = 100
	#Should End Prosperity Ore generate in the world?
	generateEndProsperityOre = true
	#The maximum amount of End Inferium Ore blocks that can spawn in a vein.
	#Range: > 0
	endInferiumSpawnSize = 4
	#The maximum Y level that End Inferium Ore veins can spawn.
	#Range: 0 ~ 128
	endInferiumSpawnHeight = 100
	#Should Nether Prosperity Ore generate in the world?
	generateNetherProsperityOre = true
	#Should Nether Inferium Ore generate in the world?
	generateNetherInferiumOre = true
	#The maximum Y level that Prosperity Ore veins can spawn.
	#Range: 0 ~ 128
	endProsperitySpawnHeight = 100
	#How many End Prosperity Ore veins should spawn in a chunk.
	#Range: > 0
	endProsperitySpawnRate = 3
	#The maximum amount of End Prosperity Ore blocks that can spawn in a vein.
	#Range: > 0
	endProsperitySpawnSize = 4
	#The maximum amount of Nether Prosperity Ore blocks that can spawn in a vein.
	#Range: > 0
	netherProsperitySpawnSize = 3
	#How many Nether Prosperity Ore veins should spawn in a chunk.
	#Range: > 0
	netherProsperitySpawnRate = 2
	#The maximum Y level that Nether Prosperity Ore veins can spawn.
	#Range: 0 ~ 128
	netherProsperitySpawnHeight = 100
	#Should End Inferium Ore generate in the world?
	generateEndInferiumOre = true

