
[general]
	"Show entities with full health" = true
	"Height Above Mob" = 0.6
	"Group Armor (condense 5 iron icons into 1 diamond icon)" = true
	"Display on Players" = true
	"Plate Size (Boss)" = 50
	"Show Max HP" = true
	"Max Distance" = 12
	"Show Attributes" = true
	"Show Current HP" = true
	"Show Debug Info with F3" = true
	"Background Padding" = 2
	"HP Text Height" = 14
	"Only show the health bar for the entity looked at" = false
	"Draw Background" = true
	"Plate Size" = 25
	"Display on Bosses" = true
	"Background Height" = 6
	"Show Armor" = true
	"Health Bar Height" = 4
	"Color Health Bar by Type (instead of health percentage)" = false
	"Show HP Percentage" = true
	#Blacklist uses entity IDs, not their display names. Use F3 to see them in the Neat bar.
	Blacklist = ["minecraft:shulker", "minecraft:armor_stand", "minecraft:cod", "minecraft:salmon", "minecraft:pufferfish", "minecraft:tropical_fish", "eyesinthedarkness:eyes", "artifacts:mimic", "minecraft:bat", "aquaculture:arapaima", "aquaculture:arrau_turtle", "aquaculture:atlantic_cod", "aquaculture:atlantic_halibut", "aquaculture:atlantic_herring", "aquaculture:bayad", "aquaculture:blackfish", "aquaculture:bluegill", "aquaculture:boulti", "aquaculture:box_turtle", "aquaculture:brown_shrooma", "aquaculture:brown_trout", "aquaculture:capitaine", "aquaculture:carp", "aquaculture:catfish", "aquaculture:gar", "aquaculture:jellyfish", "aquaculture:minnow", "aquaculture:muskellunge", "aquaculture:pacific_halibut", "aquaculture:perch", "aquaculture:pink_salmon", "aquaculture:piranha", "aquaculture:pollock", "aquaculture:rainbow_trout", "aquaculture:red_grouper", "aquaculture:red_shrooma", "aquaculture:smallmouth_bass", "aquaculture:starshell_turtle", "aquaculture:synodontis", "aquaculture:tambaqui", "aquaculture:tuna", "endergetic:puff_bug", "rats:rat"]
	"Render with Interface Disabled (F1)" = false

