
[general]
	"Show entities with full health" = true
	"Height Above Mob" = 0.6
	"Group Armor (condense 5 iron icons into 1 diamond icon)" = true
	"Display on Players" = true
	"Plate Size (Boss)" = 50
	"Show Max HP" = true
	"Max Distance" = 12
	"Show Attributes" = true
	"Show Current HP" = true
	"Show Debug Info with F3" = true
	"Background Padding" = 2
	"HP Text Height" = 14
	"Only show the health bar for the entity looked at" = false
	"Draw Background" = true
	"Plate Size" = 25
	"Display on Bosses" = true
	"Background Height" = 6
	"Show Armor" = true
	"Health Bar Height" = 4
	"Color Health Bar by Type (instead of health percentage)" = false
	"Show HP Percentage" = true
	#Blacklist uses entity IDs, not their display names. Use F3 to see them in the Neat bar.
	Blacklist = ["alexsmobs:blobfish", "alexsmobs:bone_serpent_part", "alexsmobs:centipede_body", "alexsmobs:centipede_tail", "alexsmobs:cockroach", "alexsmobs:crow", "alexsmobs:fly", "alexsmobs:hummingbird", "alexsmobs:lobster", "alexsmobs:rattlesnake", "alexsmobs:roadrunner", "ars_nouveau:sylph", "artifacts:mimic", "bellybutton:dust_bunny", "betterendforge:dragonfly", "druidcraft:lunar_moth", "dungeons_mobs:poison_quill_vine", "dungeons_mobs:quick_growing_vine", "eyesinthedarkness:eyes", "fins:banded_redback_shrimp", "fins:blu_wee", "fins:flatback_leaf_snail", "fins:flatback_sucker", "fins:golden_river_ray", "fins:high_finned_blue", "fins:ornate_bugfish", "fins:pea_wee", "fins:penglil", "fins:phantom_nudibranch", "fins:red_bull_crab", "fins:river_pebble_snail", "fins:siderol_whiskered_snail", "fins:spindly_gem_crab", "fins:swamp_mucker", "fins:teal_arrowfish", "fins:vibra_wee", "fins:wee_wee", "fins:white_bull_crab", "forbidden_arcanus:pixie", "gaiadimension:cavern_tick", "gaiadimension:markuzar_plant", "jellyfishing:blue_jellyfish", "jellyfishing:jellyfish", "minecraft:armor_stand", "minecraft:bat", "minecraft:bee", "minecraft:cod", "minecraft:creeper", "minecraft:dolphin", "minecraft:endermite", "minecraft:pufferfish", "minecraft:salmon", "minecraft:shulker", "minecraft:silverfish", "minecraft:tropical_fish", "more_jellyfish:brown_fungal_jellyfish", "more_jellyfish:clay_jellyfish", "more_jellyfish:coal_jellyfish", "more_jellyfish:cow_jellyfish", "more_jellyfish:creeper_jellyfish", "more_jellyfish:crimson_fungal_jellyfish", "more_jellyfish:diamond_jellyfish", "more_jellyfish:emerald_jellyfish", "more_jellyfish:glowstone_jellyfish", "more_jellyfish:gold_jellyfish", "more_jellyfish:guardian_jellyfish", "more_jellyfish:honey_jellyfish", "more_jellyfish:iron_jellyfish", "more_jellyfish:lapis_lazuli_jellyfish", "more_jellyfish:netherite_jellyfish", "more_jellyfish:quartz_jellyfish", "more_jellyfish:red_fungal_jellyfish", "more_jellyfish:redstone_jellyfish", "more_jellyfish:skellyfish", "more_jellyfish:slime_jellyfish", "more_jellyfish:sponge_jellyfish", "more_jellyfish:warped_fungal_jellyfish", "mysticalworld:beetle", "mysticalworld:deer", "mysticalworld:frog", "mysticalworld:hell_sprout", "mysticalworld:owl", "mysticalworld:silkworm", "mysticalworld:sprout", "rats:rat", "statues:statue_bat", "undergarden:gwibling", "waddles:adelie_penguin"]
	"Render with Interface Disabled (F1)" = false

