
[General]
	#The message sent on preventspread blocks found.
	messageOnPreventSpreadBlocksFound = "As you place the last %preventSpreadBlockString%, you feel annoyed that you bothered doing this."
	#The amount of blocks that are instantly converted to a nether block around a portal when it is detected. If there are existing nether blocks within the radius, their count is substracted from this number.
	#Range: 0 ~ 1000
	instantConvertAmount = 100
	#When enabled, sends a message to players around the portal when it is broken.
	sendMessageOnPortalBroken = true
	#The amount of prevent-spread-blocks (defined) needed within the radius of the nether portal to prevent spread.
	preventSpreadBlockAmountNeeded = 13
	#When enabled, blocks the spread effect when there are n (defined) prevent-spread-blocks (defined) within the radius.
	preventSpreadWithBlock = true
	#The radius around the portal to which the nether blocks can spread.
	#Range: 1 ~ 100
	portalSpreadRadius = 50
	#The delay in ms in between the spread around the nether portal.
	#Range: 20 ~ 360000
	spreadDelay = 2000
	#When enabled, shows the portal coordinates in portal messages.
	prefixPortalCoordsInMessage = true
	#The block which prevents the nether portal from spreading. By default a coal block (minecraft:coal_block is the namespace ID).
	preventSpreadBlockString = "extendedcrafting:crystaltine_block"
	#The message sent on portal creation.
	messageOnPortalCreation = "As the portal opens, a feeling of dread begins to permeate the surroundings. The Nether's foul influence will seep into the Overworld unless %preventSpreadBlockAmountNeeded% %preventSpreadBlockString% are placed within a %portalSpreadRadius%-block radius of the portal. Yes, you read that correctly."
	#When enabled, sends a message to players around the portal that the nether spread has stopped when the portal detects new 'preventSpreadBlockString' blocks.
	sendMessageOnPreventSpreadBlocksFound = true
	#The message sent when a portal is broken.
	messageOnPortalBroken = "You've broken the Nether portal. Good job I guess?"
	#When enabled, sends a message to players around the portal that the nether is spreading and that you can stop the spread with 'preventSpreadBlockAmountNeeded' of the 'preventSpreadBlockString' block.
	sendMessageOnPortalCreation = true

