
#General settings
[general]
	#Minimum speed a sword can have.
	#Range: -4.0 ~ 4.0
	sword_speed = -2.4
	#Weight of a golden case dropping
	#Range: 0 ~ 100
	gold_chance = 35
	#Initital Max XP for tools.
	#Range: 0 ~ 10000
	init_xp = 256
	#Range: 0 ~ 100
	gold_rolls = 5
	#Chance of a case dropping
	#Range: 0 ~ 100
	total_chance = 5
	#Minimum damage a pickaxe can do.
	#Range: 0 ~ 100
	pick_damage = 3
	#Weight of a titan case dropping
	#Range: 0 ~ 100
	titan_chance = 20
	#Minimum damage a sword can do.
	#Range: 0 ~ 100
	sword_damage = 7
	#Minimum attack speed a pickaxe can have.
	#Range: -4.0 ~ 4.0
	pick_a_speed = -2.8
	#Weight for pick to drop from case
	#Range: 0 ~ 100
	pick_weight = 15
	#Weight of a basic case dropping
	#Range: 0 ~ 100
	basic_chance = 70
	#Range: 0 ~ 100
	titan_rolls = 9
	#Initital Rolls for traits/stats
	#Range: 0 ~ 100
	basic_rolls = 2
	#Weight for sword to drop from case
	#Range: 0 ~ 100
	sword_weight = 20

