
#General settings
[general]
	#Minimum speed a sword can have.
	#Range: -4.0 ~ 4.0
	sword_speed = -2.4
	#Weight of a golden case dropping
	#Range: 0 ~ 100
	gold_chance = 35
	#Initital Max XP for tools.
	#Range: 0 ~ 10000
	init_xp = 256
	#Range: 0 ~ 100
	gold_rolls = 5
	#Chance of a case dropping
	#Range: 0 ~ 100
	total_chance = 5
	#Minimum damage a pickaxe can do.
	#Range: 0 ~ 100
	pick_damage = 3
	#Weight of a titan case dropping
	#Range: 0 ~ 100
	titan_chance = 20
	#Minimum damage a sword can do.
	#Range: 0 ~ 100
	sword_damage = 7
	#Weight for a shovel to drop from case
	#Range: 0 ~ 100
	spade_weight = 8
	#Minimum attack speed a shovel can have.
	#Range: -4.0 ~ 4.0
	spade_a_speed = -3.0
	#Minimum attack speed a pickaxe can have.
	#Range: -4.0 ~ 4.0
	pick_a_speed = -2.8
	#Weight for a pick to drop from case
	#Range: 0 ~ 100
	pick_weight = 15
	#Weight of a basic case dropping
	#Range: 0 ~ 100
	basic_chance = 70
	#Minimum damage a shovel can do.
	#Range: 0 ~ 100
	spade_damage = 4
	#Weight for and axe to drop from case
	#Range: 0 ~ 100
	axe_weight = 10
	#Range: 0 ~ 100
	titan_rolls = 9
	#Weight for a bow to drop from case
	#Range: 0 ~ 100
	bow_weight = 8
	#Initital Rolls for traits/stats
	#Range: 0 ~ 100
	basic_rolls = 2
	#Minimum damage an axe can do.
	#Range: 0 ~ 100
	axe_damage = 9
	#Weight for a sword to drop from case
	#Range: 0 ~ 100
	sword_weight = 20
	#Minimum attack speed an axe can have.
	#Range: -4.0 ~ 4.0
	axe_a_speed = -3.0

#Traits Enabled
[traits]
	#Weakening Enabled?
	weakening_enabled = true
	#Webbed Enabled?
	webbed_enabled = true
	#More_fire_resistant Enabled?
	more_fire_resistant_enabled = true
	#Very_weakening Enabled?
	very_weakening_enabled = true
	#Floating Enabled?
	floating_enabled = true
	#More_resistant Enabled?
	more_resistant_enabled = true
	#Speedier Enabled?
	speedier_enabled = true
	#Damage++ Enabled?
	"damage++_enabled" = true
	#Bouncier Enabled?
	bouncier_enabled = true
	#Soul_searching Enabled?
	soul_searching_enabled = true
	#Regenerating Enabled?
	regenerating_enabled = true
	#Hastey Enabled?
	hastey_enabled = true
	#Super_lucky Enabled?
	super_lucky_enabled = true
	#Auto-smelt Enabled?
	auto-smelt_enabled = true
	#Very_withering Enabled?
	very_withering_enabled = true
	#Resistant Enabled?
	resistant_enabled = true
	#Bouncy Enabled?
	bouncy_enabled = true
	#Hastier Enabled?
	hastier_enabled = true
	#Cloud_walker Enabled?
	cloud_walker_enabled = true
	#Very_poisonous Enabled?
	very_poisonous_enabled = true
	#Insightful Enabled?
	insightful_enabled = true
	#Glittering Enabled?
	glittering_enabled = true
	#Filling Enabled?
	filling_enabled = true
	#Strong Enabled?
	strong_enabled = true
	#Fire_resistant Enabled?
	fire_resistant_enabled = true
	#Poisonous Enabled?
	poisonous_enabled = true
	#Fortified Enabled?
	fortified_enabled = true
	#Double_webbed Enabled?
	double_webbed_enabled = true
	#Damage+ Enabled?
	"damage+_enabled" = true
	#Deep_breathing Enabled?
	deep_breathing_enabled = true
	#Withering Enabled?
	withering_enabled = true
	#Explosive Enabled?
	explosive_enabled = true
	#Phasing Enabled?
	phasing_enabled = true
	#Stronger Enabled?
	stronger_enabled = true
	#Lucky Enabled?
	lucky_enabled = true
	#Speedy Enabled?
	speedy_enabled = true
	#Blinding Enabled?
	blinding_enabled = true

