
["Feature Options"]

	["Feature Options".Misc]
		#
		# Add 2x2 Swamp Trees to modded swamp biomes.
		addLargeSwampTreeModdedBiomes = false
		#
		# Adds giant boulders to modded Giant Tree Taiga (or Redwood) biomes.
		addGiantBouldersModdedBiomes = false
		#
		# Add the ID/resource location of the biome you don't want
		# RS's 2x2 Swamp trees to spawn in. Separate each ID with a comma ,
		#
		#Example: "minecraft:ice_spikes,awesome_mod:awesome_biome"
		blacklistedSwampTreeBiomes = "undergarden:barren_abyss,undergarden:dense_forest,undergarden:forgotten_field,undergarden:otherside,undergarden:smog_spires,undergarden:smogstem_forest,undergarden:wigglewood_forest,mahoutsukai:marble"
		#
		# Add the ID/resource location of the biome you don't want
		# RS's boulders to spawn in. Separate each ID with a comma ,
		#
		#Example: "minecraft:ice_spikes,awesome_mod:awesome_biome"
		blacklistedBoulderBiomes = "undergarden:barren_abyss,undergarden:dense_forest,undergarden:forgotten_field,undergarden:otherside,undergarden:smog_spires,undergarden:smogstem_forest,undergarden:wigglewood_forest,mahoutsukai:marble"
		#
		# How many Giant Boulders per chunk. (Can be decimal too)
		#Range: 0.0 ~ 100.0
		giantBouldersPerChunk = 0.1
		#
		# Adds tiny boulders to modded Taiga biomes.
		addTinyBouldersModdedBiomes = false
		#
		# Adds a large tree somewhat uncommonly to Swamp biome and replaces
		# all vanilla trees in Swamp Hills biome with the larger tree.
		hornedSwampTree = true
		#
		# Adds tiny boulders to Taiga Mountains and Snowy Taiga Mountains biomes 
		# that can contain small amounts of Coal and Iron ores.
		boulderTiny = true
		#
		# 1 out of ___ chance of Diamond Ore when placing
		# a block in giant Boulders. Lower number = more common.
		# Enter 0 to disable Diamond Ores completely.
		#Range: 0 ~ 1000000
		diamondChanceInGiantBoulders = 7000
		#
		# Replaces boulders in Giant Tree Taiga Hills and Giant Spruce Taiga Hills
		# biomes with a larger boulder that can contain Coal, Iron, and extremely
		# rarely, can also have Diamond Ores.
		boulderGiant = true

["Structure Options"]

	["Structure Options".Igloos]
		#
		# Add Grassy Igloos to modded biomes that are
		# most likely grassy fields or temperate forests.
		addGrassyIglooToModdedBiomes = true
		#
		# Add the ID/resource location of the biome you don't want
		# RS's Igloos to spawn in. Separate each ID with a comma ,
		#
		#Example: "minecraft:ice_spikes,awesome_mod:awesome_biome"
		blacklistedIglooBiomes = "undergarden:barren_abyss,undergarden:dense_forest,undergarden:forgotten_field,undergarden:otherside,undergarden:smog_spires,undergarden:smogstem_forest,undergarden:wigglewood_forest,mahoutsukai:marble"
		#
		# How rare are Stone Igloos in Giant Tree Taiga biomes.
		# 
		# 1 for spawning in most chunks and 1001 for no spawn.
		#Range: 1 ~ 1001
		stoneIglooSpawnrate = 22
		#
		# How rare are Grassy Igloos in Plains and Forests.
		# 
		# 1 for spawning in most chunks and 1001 for no spawn.
		#Range: 1 ~ 1001
		grassyIglooSpawnrate = 22
		#
		# Add Stone Igloos to modded biomes that are
		# most likely Giant Tree Taiga variants.
		addStoneIglooToModdedBiomes = true

	["Structure Options"."Jungle Fortress"]
		#
		# How rare are Jungle Fortresses.
		# 
		# 1 for spawning in most chunks and 1001 for no spawn.
		#Range: 1 ~ 1001
		jungleFortressSpawnrate = 36
		#
		# Controls whether loot chests spawn or not in Jungle Fortresses.
		lootChestsJF = true
		#
		# Add the ID/resource location of the biome you don't want
		# RS's Jungle Fortresses to spawn in. Separate each ID with a comma ,
		#
		#Example: "minecraft:ice_spikes,awesome_mod:awesome_biome"
		blacklistedFortressBiomes = "undergarden:barren_abyss,undergarden:dense_forest,undergarden:forgotten_field,undergarden:otherside,undergarden:smog_spires,undergarden:smogstem_forest,undergarden:wigglewood_forest,mahoutsukai:marble"
		#
		# Add Jungle Fortress to modded jungle biomes.
		addJungleFortressToModdedBiomes = true
		#
		# How often Silverfish Blocks will generate in Jungle Fortress as a percentage.
		# Note: Mossy Stone Bricks block cannot be infected by Silverfish
		# 
		# 0 for no Silverfish Blocks and 100 for max spawnrate.
		#Range: 0.0 ~ 100.0
		silverfishSpawnrateJF = 0.5
		#
		# Silverfish Mob Spawners generate in Stone Fortresses.
		# If turned off, the spawners will become Skeleton spawners.
		allowSilverfishSpawnerJF = true

