
[General]
	#Max Y-Level Ore's Spawn
	maxYLevel = 60
	#Time to change Harden Candy to Blank Candy in seconds.
	changeTime = 2
	#Max Saturation for Rock Candy
	satValue = 0.6
	#Ore's Per Vein
	veinSize = 4
	#Min Y-Level Ore's Spawn
	minYLevel = 15
	#Spawn Rate
	spawnRate = 4
	#Max Food Value for Rock Candy
	foodValue = 5

