
[Entities]
	#Range: 1 ~ 1000000
	tinkywinky_weight = 7
	#Range: 1 ~ 1000000
	dipsy_weight = 7
	#Range: 1 ~ 1000000
	laalaa_weight = 7
	#Range: 1 ~ 1000000
	po_weight = 7
	#Range: 1 ~ 1000000
	noonoo_weight = 7
	#Range: 1 ~ 1000000
	mimi_weight = 3
	#Range: 1 ~ 1000000
	daadaa_weight = 3
	#Range: 1 ~ 1000000
	ping_weight = 3
	#Range: 1 ~ 1000000
	ba_weight = 3
	#Range: 1 ~ 1000000
	ruru_weight = 3
	#Range: 1 ~ 1000000
	nin_weight = 3
	#Range: 1 ~ 1000000
	duggledee_weight = 3
	#Range: 1 ~ 1000000
	umpiepumpie_weight = 3
	#Range: 1 ~ 1000000
	tinkywinky_zombie_weight = 30
	#Range: 1 ~ 1000000
	dipsy_zombie_weight = 30
	#Range: 1 ~ 1000000
	laalaa_zombie_weight = 30
	#Range: 1 ~ 1000000
	po_zombie_weight = 30
	#Chance of Teletubby transforming into zombie Teletubby
	#Range: 1 ~ 100
	transformation_probability = 20

[Food]
	#Range: 1 ~ 100
	custard_hunger = 5
	#Range: 1.0 ~ 100.0
	custard_saturation = 1.5
	#Range: 1 ~ 100
	toast_hunger = 2
	#Range: 1.0 ~ 100.0
	toast_saturation = 1.0

[WorldGen]
	#Voice Trumpet Spawnrate (%)
	#Range: 0 ~ 100
	probability = 2
	#Min chunks between domes
	#Range: 1 ~ 1000
	min = 15
	#Max chunks between domes
	#Range: 1 ~ 1000
	max = 30

