
#Settings for the Minimap
[minimap]
	#X Position of the Minimap
	#Range: -500 ~ 500
	posX = -65
	#Y Position of the Minimap
	#Range: -500 ~ 500
	posY = 1
	#Is Minimap visible?
	visible = true
	#Set this to true and the minimap will spin in the direction you're facing
	Spin = false
	#Scale of the Minimap
	#Range: 0.25 ~ 4.0
	scale = 1.0
	#Selected Style (don't change this manually)
	style = "default"
	#Alignment of the Minimap
	#Allowed Values: TOP_LEFT, TOP, TOP_RIGHT, LEFT, CENTER, RIGHT, BOTTOM_LEFT, BOTTOM, BOTTOM_RIGHT
	alignment = "TOP_RIGHT"

#Settings for the Compass (Unused right now)
[compass]
	#X Position of the Compass
	#Range: -500 ~ 500
	posX = -128
	#Y Position of the Compass
	#Range: -500 ~ 500
	posY = 1
	#Is Compass visible?
	visible = true
	#Scale of the Compass
	#Range: 0.25 ~ 4.0
	scale = 1.0
	#Selected Style (don't change this manually)
	style = "default"
	#Alignment of the Compass
	#Allowed Values: TOP_LEFT, TOP, TOP_RIGHT, LEFT, CENTER, RIGHT, BOTTOM_LEFT, BOTTOM, BOTTOM_RIGHT
	alignment = "TOP"

