
#Trumpet Skeleton spawn settings
[spawning]
	#Spawn weight relative to normal skeleton spawns. Multiplied with normal skeleton spawn weight.
	#For example, the default value of 0.05 (aka 1/20) means that normal skeletons will be 20 times more common than trumpet skeletons.
	#Range: 0.0 ~ 2.147483647E9
	relative_spawn_weight = 0.05

