
[common]

	[common.worldgen]
		#Set to 'DEFAULT' to only generate the normally textured waystones. Set to 'MOSSY' or 'SANDY' to generate all as that variant. Set to 'BIOME' to make the style depend on the biome it is generated in.
		#Allowed Values: DEFAULT, MOSSY, SANDY, BIOME
		worldGenStyle = "BIOME"
		#EXPERIMENTAL: Set to true if waystones should be added to the generation of villages. NOTE THAT THIS IS CURRENTLY NOT LIMITED TO ONLY ONE WAYSTONE, THEREFORE IT IS NOT RECOMMENDED RIGHT NOW.
		addVillageStructure = false
		#Approximate chunk distance between waystones generated freely in world generation. Set to 0 to disable generation.
		#Range: > 0
		worldGenFrequency = 50
		#The Name Generator will pick from these names until they have all been used, then it will generate random ones again.
		customWaystoneNames = ["Home Depot", "Costco", "Red Lobster", "Darkest Armpit", "Dankington", "What Is Love", "Dunkin Donuts", "Blockbuster Video", "Look Behind You", "jk roflmao", "Here", "There", "Over Yonder", "Taco Palace", "Updog", "House of 1000 Snakes", "Another Waystone", "High Fives", "Descent Into Madness", "Diagon Alley", "Winner Winner Chicken Dinner", "Cybertron", "Cobra Kai Dojo", "Run's House", "Chuck E. Cheese", "Somewhere", "Hopeulikit", "Sponsored by Nvidia", "Flarb", "Grungingham", "Potato Town", "SCREEE", "#2", "#waystone", "Mambo No. 5"]

