
[The_End]
	#
	#Does BYG control The End?
	ControlEnd = true
	#
	#Is the list of biomes a blacklist or whitelist?
	#When this list is a blacklist, the values in the list will not be in world generation.
	#When this list is a whitelist, Adding a biome several times gives it more weight in generation and it must contain at least 1 value.
	#When set to true, datapack biomes will work automatically!
	#Default: true
	isBlacklistEnd = true
	#
	#End Biome Size.
	#Default: 3
	#Range: 0 ~ 10
	IslandBiomeSize = 3
	#
	#This works as a whitelist or blacklist depending on the "isBlacklistEnd" value.
	#NO SPACES AFTER COMMAS!
	#DOES NOT ACCEPT DATAPACK VALUES!
	#Default: "byg:viscal_isles,byg:shattered_viscal_isles,minecraft:small_end_islands,minecraft:the_end,minecraft:end_barrens"
	BlacklistEnd = "byg:viscal_isles,byg:shattered_viscal_isles,minecraft:small_end_islands,minecraft:the_end,minecraft:end_barrens"
	#
	#End Biome Size
	#Default: 3
	#Range: 0 ~ 10
	EndBiomeSize = 3

	[The_End.Void]
		#
		#Add biomes by their registry String ID's in a commented list.
		#Adding a biome several times gives it more weight in generation.
		#NO SPACES AFTER COMMAS!
		#DOES NOT ACCEPT DATAPACK VALUES!
		#Default: "byg:viscal_isles,byg:shattered_viscal_isles,minecraft:small_end_islands"
		VoidBiomes = "byg:viscal_isles,byg:shattered_viscal_isles,minecraft:small_end_islands"
		#
		#Void Biome(where small end islands generate in vanilla) size.
		#Default: 3
		#Range: 0 ~ 10
		VoidBiomeSize = 2

[The_Nether]
	#
	#Is the list of biomes a blacklist or whitelist?
	#When this list is a blacklist, the values in the list will not be in world generation.
	#When this list is a whitelist, Adding a biome several times gives it more weight in generation and it must contain at least 1 value.
	#When set to true, datapack biomes will work automatically!
	#Default: true
	isBlacklistNether = true
	#
	#Nether Biome Size
	#Default: 3
	#Range: 0 ~ 10
	NetherBiomeSize = 3
	#
	#Does BYG control The Nether?
	ControlNether = true
	#
	#This works as a whitelist or blacklist depending on the "isBlacklistNether" value.
	#NO SPACES AFTER COMMAS!
	#DOES NOT ACCEPT DATAPACK VALUES!
	#Default: ""
	BlacklistNether = ""

